import json, re
HEAD=("The attached reference snaps define the style of this image: match their exact image quality, softness, colours, framing and the look of the caption bar. "
"The attached character images define ONLY the person's face, hair and clothes, never the image style. This is a real photograph taken with a phone, NOT an illustration, NOT CGI, NOT a render, NOT a film still, nothing posed or arranged. "
"A screenshot of a Snapchat snap from 2015, a quick photo taken on an old iPhone by a teenage student {how}, taken in one second without aiming. "
"Old phone camera quality exactly like the reference snaps: soft focus, gentle sensor noise, mild JPEG compression, slightly flat muted colours {cast}, plain room light, no HDR, no depth-of-field effect, no cinematic lighting. "
"Casual handheld framing, a little tilted, people cut off at the edges, and part of me very close to the lens in the foreground, blurred: {fore}. Nobody is posing for the photo, nobody looks at the camera, nobody has noticed the phone, everyone is just doing what they were doing. "
"Setting looks like the real film sets of a gothic wizarding boarding school, students in black robes with white shirts, grey jumpers and striped house ties. "
"{scene} Across the screen, in the lower half, a Snapchat caption bar: a semi-transparent black rectangle at 60 percent opacity spanning the full width, with one line of small white Helvetica lowercase text, centred, perfectly sharp, reading exactly: {caption}. "
"No other interface, no watermark. Vertical 9:16, full-bleed.")
FORE=["my hand holding a goblet","the back of my friend's head","my knee in jeans on the sofa","my hand on the banister","the rim of my plate and my fork","my sleeve and the tip of my broom","the rim of my cauldron and my sleeve","my open book and my elbow","my shoe on the bed frame","my glove and a snowflake on the lens","my goblet and my thumb over the corner of the lens","the door frame and my shoulder","a clay pot and my muddy fingers","my knee and the edge of the boat","my bag strap and my thumb","my scarf blown across the corner of the lens","my toast and my thumb","my blanket and my knee"]
W="with a warm yellow cast from candles, blown-out windows"; G="with a cold grey cast, blown-out white sky"
S=[
("theo lost a bet","Theo","while walking past the table",W,"The dining hall at breakfast, long tables, the backs of students' heads blurred in the foreground. Half cut off on the right, @Theo, green-silver tie, sits at the table with a red-gold scarf wrapped round his neck, looking down at his plate, mid-chew."),
("maja's first spell.","Maja","from my desk",W,"A bright classroom, the back of a student's head blurred in the bottom left. Two desks ahead, @Maja, blue-bronze tie, holds her wand loosely and looks sideways out of the window with a bored face, a small wisp of black smoke rising from the feather on her desk, nobody else has noticed yet."),
("nova joined the chess club.","Nova","from the sofa","with a warm cast from a fire, dark corners","A dim common room, the arm of a leather sofa blurred in the foreground. Across the room, @Nova, green-silver tie, sits at a small table with a chess board, chin on her hand, looking at the board, two white pieces lying knocked over on the floor beside the table leg."),
("finn vs the staircase round 3","Finn","from the landing","with a cold cast from high windows","A stone stairwell with portraits, a banister blurred in the foreground. Halfway up a staircase that is slightly tilted as it moves, @Finn, yellow-black tie, stands gripping the rail with both hands, looking down at his feet with a tense face, his bag hanging off one shoulder. Two students further up looking back over their shoulders."),
("ollie's owl.","Ollie","across the table",W,"The dining hall at breakfast. Right across the table, @Ollie, yellow-black tie, is looking down at a tiny grey owl the size of a tennis ball standing on his plate next to a sandwich, his mouth slightly open, a goblet blurred in the foreground, a student's shoulder cutting off the right edge."),
("cara at 6am","Cara","while walking onto the pitch","with a cold blue-grey cast, thick fog","A foggy quidditch pitch at dawn, the goal towers half hidden in mist. Ahead of me on the wet grass, @Cara, blue scarf, walks away from the camera with a broomstick over one shoulder, her breath visible in the cold, nobody else on the pitch."),
("the dungeon smells again","Lena, Theo","from my bench","with a cold cast from candles and a purple haze","The dungeon potions classroom, thin purple smoke hanging in the air, a jar and a candle blurred in the foreground. Across the bench, @Lena, red-gold tie, stirs a cauldron and looks down into it. Next to her @Theo, green-silver tie, has his sleeve pulled over his nose and is looking off to the side."),
("study group","Nova, Maja, Ollie","from across the table","with a warm cast from a green lamp, dark","The library at night, one green lamp, open books blurred in the foreground. At the table, @Maja, blue-bronze tie, has her head down on her arms, @Ollie, yellow-black tie, leans back in his chair with his eyes closed, and @Nova, green-silver tie, is writing with her head down."),
("he said he's fine","Finn, Cara","from the foot of the bed","with a warm cast from lamps, blown-out windows","A bright hospital wing with white iron beds. In the bed, @Finn, yellow-black tie loosened, sits propped on pillows with a bandage round his head, looking down at a book. On a chair beside the bed, cut off at the edge of the frame, @Cara, blue scarf, is eating grapes and looking at her phone."),
("first snow","Ollie, Maja","while walking across the courtyard","with a cold grey cast, blown-out white sky, snow falling","A snowy cloister courtyard, snowflakes close to the lens. A few steps ahead, @Ollie, yellow-black tie, walks with his head tipped back and his mouth open, catching snow,. Further back, @Maja, blue-bronze tie, lies flat on her back in the snow with her arms out, small and half out of focus."),
("she brought the owl to breakfast.","Cara","across the table",W,"The dining hall at breakfast, a goblet and a plate blurred in the foreground. Right across the table, @Cara, blue scarf, is eating porridge and looking down at her bowl while a brown barn owl sits on her shoulder with its eyes half closed. A boy next to her is looking at the owl, cut off at the edge."),
("detention with theo","Theo, Finn","from the doorway","with a warm gold cast from candles reflecting off metal","A dim trophy room with glass cabinets full of cups. In the foreground, @Finn, yellow-black tie, kneels with his back half to me, scrubbing a cup with a rag. Further back, @Theo, green-silver tie, sits on a cabinet with his feet up, looking at his own reflection in a shield."),
("nova's plant","Nova","across the greenhouse table","with a soft green cast from steamed-up glass","The steamy greenhouse, clay pots blurred in the foreground. Across the table, @Nova, green-silver tie, stands with her arms crossed looking down at a potted plant with a wide toothy mouth that has curled up small in its pot, her face blank. Two students behind her working, not looking."),
("the boats again","Lena, Maja","from the back of the boat",G,"A small wooden boat on a grey lake, the castle far away on the cliff, the edge of the boat blurred in the foreground. In front of me, @Lena, red-gold tie, rows with both oars, looking down at the oars with a red face. Behind her in the bow, @Maja, blue-bronze tie, lies on her back with her eyes closed, one hand hanging over the side."),
("lost in the castle day 2","Ollie","while walking down the corridor","with a cold cast from one window, dark","A long empty stone corridor with portraits. Ahead of me, @Ollie, yellow-black tie, sits on the floor against the wall with his bag open, eating a pastry, looking at the pastry mid-bite. In the portrait above him, an old painted wizard is looking down at him with a frown."),
("quidditch tryouts","Cara, Finn","from the edge of the pitch",G,"A grass pitch in front of a wooden stand. Off to the left and half out of frame, @Cara, blue scarf, sits on a broomstick hovering at waist height, looking down at the broom handle and adjusting her grip. Nearer to me, @Finn, yellow-black tie, stands with his back to me holding a broom upside down, looking at it."),
("he got the howler","Theo, Nova","across the table",W,"The dining hall at breakfast, a jug blurred in the foreground. Across the table, @Theo, green-silver tie, is looking down at a red envelope lying on his plate, his fork stopped halfway. Next to him @Nova, green-silver tie, keeps eating and doesn't look up. A student further along is looking over."),
("astronomy homework","Lena, Maja","from the floor of the tower","with a cold blue cast from moonlight, very dark and grainy","The top of the stone astronomy tower at night, a candle blurred in the bottom corner. @Lena, red-gold tie, kneels over a star chart with a ruler, looking down at it. Next to her @Maja, blue-bronze tie, sits wrapped in a blanket with her head leaning against the brass telescope, eyes closed."),
]
clips=[dict(n=i,title=t,attach=a,note=f"Video {1 if i<=9 else 2}",img=HEAD.format(how=h,cast=c,scene=s,caption=t,fore=FORE[i-1])) for i,(t,a,h,c,s) in enumerate(S,1)]
WORLDS=[dict(key="hp",name="Wizarding World",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('batch-02.html',encoding='utf-8').read()
h=h.replace('<title>Snap Startframes 02</title>','<title>Wizarding Startframes 02 Redo</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=h.replace('Batch 02: zwei Videos à 9 Clips, nur Bild-Prompts. Bilder erzeugen, mir mit Clip-Nummer schicken, dann kommen die Video-Prompts.','Wizarding Batch 02, neu: 18 Startframes als zufällige Snaps, nichts gestellt. Bilder erzeugen, mir mit Clip-Nummer schicken, dann passe ich die Video-Prompts an.')
open('hp-startframes-02b.html','w',encoding='utf-8').write(h)
print(len(clips))
