import sys, json, re
sys.path.insert(0,'.')
from data import HP_IMG, PK_IMG, W, G
HP = [
# Video 1
("theo lost a bet","Theo, Cara",W,"Inside the crowded candlelit dining hall at breakfast. Right across the table from me, @Theo, green-silver tie, sits with his arms crossed and a furious face while wearing a huge red-gold knitted scarf wrapped three times around his neck and a red-gold bobble hat pulled down over his ears. Next to him @Cara, blue scarf, leans into frame grinning from ear to ear and pointing at him. Students at the next table staring."),
("maja's first spell","Maja, Lena",W,"A bright stone classroom with rows of wooden desks and tall windows. Right in front of me, @Maja, blue-bronze tie, sits with her wand held loosely in one hand and a completely calm, dreamy face while the white feather on her desk is burning with a small bright flame and black smoke. Next to her @Lena, red-gold tie, leans away with wide eyes, her own feather floating perfectly in the air. Other students turning to look, blurred."),
("nova joined the chess club","Nova","with a warm yellow cast from candles, dark corners","A dim common room corner at night with a small table and a giant wizard chess board. @Nova, green-silver tie, sits behind the board with her chin on her hand and a flat expression, while the chess pieces on her side are smashing the opposing pieces to rubble, stone splinters flying, one white knight lying broken on the floor. An empty chair opposite her, pushed back as if someone just fled."),
("finn vs the staircase round 3","Finn","with a cold cast from high windows","The vast stone stairwell with gold-framed portraits. Right in front of me, @Finn, yellow-black tie, hangs with both arms wrapped around the end of a stone banister while the staircase he is standing on swings away from the landing, one foot on the landing, one foot on the moving stair, doing a split, his bag falling into the gap. Students on the landing behind him laughing."),
("ollie's owl","Ollie",W,"The dining hall at breakfast, long wooden table with toast and goblets blurred in the foreground. Right in front of me, @Ollie, yellow-black tie, holds out both hands with a delighted face toward a tiny fluffy grey owl the size of a tennis ball that is struggling to land on the table while carrying a sandwich bigger than itself, its wings a blur. Crumbs already on Ollie's jumper."),
("cara at 6am","Cara","with a cold blue-grey cast, thick fog, blown-out sky","A foggy quidditch pitch at dawn, the tall goal towers half hidden in mist, empty wooden stands. In the middle of the wet grass, @Cara in her blue scarf and a black robe stands with a broomstick over her shoulder, a whistle in her mouth and a clipboard in her hand, pointing at the camera with an intense face. Nobody else on the pitch, dew on the grass, a lone owl on the goal hoop."),
("the dungeon smells again","Lena, Theo","with a cold cast from candles and purple smoke","The stone dungeon potions classroom with shelves of jars. Across the bench from me, @Lena, red-gold tie, stands over a cauldron pouring out thick purple smoke that fills the whole room to chest height, her ladle still in the pot, her face saying \"I know\". Next to her @Theo, green-silver tie, holds his nose with one hand and leans as far away as possible. Other students coughing, blurred, one climbing on a bench."),
("study group","Nova, Maja, Ollie","with a warm cast from a single green reading lamp, dark","The library at night, one green lamp on. A long table covered in open books. @Maja, blue-bronze tie, is asleep with her head on a book, @Ollie, yellow-black tie, is asleep sitting up with his mouth open and a biscuit in his hand, and in the middle @Nova, green-silver tie, sits perfectly upright, wide awake, staring straight into the camera without expression, a quill in her hand."),
("he said he's fine","Finn, Cara",W,"A long bright hospital wing with rows of white iron beds and tall windows. In the bed right in front of me, @Finn, yellow-black tie loosened, sits propped up on pillows with a bandage around his head, one arm in a sling, a bandaged finger and a bandaged foot sticking out from the blanket, giving the camera a weak thumbs up. @Cara in her blue scarf sits on the edge of the bed eating his grapes. A bottle of purple medicine on the bedside table."),
# Video 2
("first snow","Ollie, Maja","with a cold grey cast, blown-out white sky, snow falling","A snow-covered stone cloister courtyard with a frozen fountain, snow falling heavily. Right in front of me, @Ollie, yellow-black tie, stands with his head tipped back, eyes closed and mouth wide open catching snowflakes on his tongue, snow piled on his ginger curls. Next to him, only the head and one hand of @Maja, blue-bronze tie, stick out of a deep snowdrift, her face completely peaceful as if she is lying in bed."),
("she brought the owl to breakfast","Cara",W,"The dining hall at breakfast, students blurred along the long table. Right across from me, @Cara, blue scarf, eats a bowl of porridge with a completely serious face while a large brown barn owl sits on top of her head like a hat, its wings slightly spread for balance, one talon holding a strand of her curly hair. A boy next to her leaning away with his toast."),
("detention with theo","Theo, Finn","with a warm gold cast from candles reflecting off metal","A dim trophy room with glass cabinets full of gold cups and shields, hundreds of reflections. Right in front of me, @Finn, yellow-black tie, on his knees scrubbing a huge silver cup with a rag and a bucket, sweating, while @Theo, green-silver tie, sits on a cabinet behind him with his feet up, holding a rag but doing nothing, admiring his own reflection in a shield. A long row of dirty trophies still waiting."),
("nova's plant","Nova","with a soft green cast from steamed-up glass","The steamy glass greenhouse with hanging vines and clay pots. On the wooden table right in front of me, a potted plant with a wide toothy mouth has curled up as small as it can and is hiding behind its own leaves, trembling, while @Nova, green-silver tie, stands over it with folded arms staring at it without expression. The teacher's gloves lying abandoned on the table."),
("the boats again","Lena, Maja",G,"A small wooden boat on a wide dark lake at dusk, the castle on the cliff behind, other boats far away. Right in front of me, @Lena, red-gold tie, rows with both oars and a furious red face, while @Maja, blue-bronze tie, lies stretched out across the bow with her hands behind her head and her eyes closed, trailing one hand in the water. A tentacle tip just breaking the surface next to her hand, out of focus."),
("lost in the castle day 2","Ollie","with a cold cast from a high window, dark","A long empty stone corridor with dozens of gold-framed portraits, one small window at the end. Right in front of me, @Ollie, yellow-black tie, sits on the floor against the wall with his bag open, eating a pastry with a lost expression, crumbs everywhere. The painted old wizard in the portrait above him is leaning out of his frame and pointing firmly down the corridor with an exasperated face."),
("quidditch tryouts","Cara, Finn",G,"The quidditch pitch under a grey sky, wooden stands empty. Right in front of me, @Cara, blue scarf, hangs upside down from her broomstick two metres above the grass, both legs hooked over the handle, her hair hanging down, still grinning and giving a thumbs up. Below her @Finn, yellow-black tie, stands with his arms out ready to catch her, looking terrified. A pile of broomsticks on the grass."),
("he got the howler","Theo, Nova",W,"The dining hall at breakfast. Right across the table from me, @Theo, green-silver tie, sits frozen with his fork halfway to his mouth staring at a bright red envelope on his plate that is smoking at the corners and starting to curl open. Next to him @Nova, green-silver tie, has already put her fingers in her ears and closed her eyes. Students around them ducking under the table, blurred."),
("astronomy homework","Maja, Lena","with a cold blue cast from moonlight, very dark and grainy","The top of the round stone astronomy tower at night, a starry sky, a brass telescope on a stand. Right in front of me, @Lena, red-gold tie, kneels with a star chart, a ruler and a candle, measuring angles with a frown, while @Maja, blue-bronze tie, is fast asleep sitting on the floor with her cheek resting against the cold telescope, a blanket around her shoulders."),
]
PK = [
# Video 1
("rudi at the laundromat","Jonas","with a cold white cast from fluorescent lights","Inside a small laundromat with a row of washing machines and dryers. Right in front of me, @Jonas, red backwards cap, green hoodie, sits on a washing machine reading a magazine, while his small orange Charmander sits in an open dryer drum surrounded by warm laundry, one grey sock in its mouth with a black scorched hole in it, its tail flame lighting up the drum. A woman in the background staring with her basket."),
("bo made a friend","Emma",G,"A fast-food car park with a red bench. Right in front of me, @Emma, blonde ponytail, denim jacket, holds an empty paper bag upside down with a betrayed face, while her yellow Pikachu sits on the bench next to a small purple Rattata with real fur, the two of them sharing a big pile of stolen chips between them, both with their cheeks full, looking at the camera."),
("herbert on the escalator","Lukas","with a cold white cast from mall lights","Inside a shopping mall on a moving escalator. Right in front of me, @Lukas, grey hoodie with the hood up, stands asleep on the escalator step leaning against the handrail, while his yellow Psyduck, two steps above him, has both feet planted on the step and both hands on its head, staring in panic straight down at the camera, shoppers behind them out of focus."),
("mira got a fan","Mira",G,"A quiet street with hedges. Right in front of me, @Mira, long brown hair, navy rain jacket, walks toward the camera with her hands in her pockets and a dead-eyed face, wearing her red beanie, and next to her a round pink Jigglypuff waddles along wearing an identical tiny red beanie, looking up at her adoringly. Mira is not looking at it."),
("sam's new rod","Sam, Mira",G,"The wooden pier on the grey lake in the rain. Right in front of me, @Sam, black rain jacket, holds up a brand new shiny fishing rod with a price tag still hanging from it and a proud grin, and on the end of the line an orange Magikarp is already hanging, flapping. Next to him @Mira, red beanie, hood up, stares at the fish with a blank face and a coffee cup in her hand."),
("yuna vs the vending machine","Yuna","with a cold cast from a glowing vending machine, dusk","A bus shelter at dusk with a glowing drinks vending machine. Right in front of me, @Yuna, yellow raincoat, points at the machine with her arm out and a battle face, while her small blue Squirtle stands in front of it spraying a jet of water straight into the coin slot, water running down the glass. A bag of crisps stuck inside the machine visible through the glass."),
("the snorlax moved","Jonas, Lukas","with a cold cast, misty","The narrow misty country road between trees and the wooden fence, now completely empty. In the tarmac, a huge Snorlax-shaped crater with grass flattened all around it, a collapsed tent and a washing line lying in it. @Jonas, red backwards cap, stands at the edge of the crater with his hands on his hips staring into it, and @Lukas, grey hoodie, stands next to him holding a single sock, both looking at the camera."),
("group photo attempt 7","Jonas, Emma, Sam",G,"A grassy hill with a town below, grey sky. A failed group photo: @Jonas, red backwards cap, @Emma, blonde ponytail, and @Sam, black rain jacket, try to pose in a row, but the Charmander has set the edge of Sam's sleeve smoking, the Pikachu is climbing over Emma's head with a sandwich, and a Magikarp is flopping across the grass in the foreground. Everyone mid-shout, motion-blurred."),
("rain day","Jonas, Mira, Emma","with a cold grey-blue cast, heavy rain","A bus stop in pouring rain, water bouncing off the pavement. Right in front of me, @Mira, red beanie, @Emma, denim jacket, and @Jonas, green hoodie, squeeze together under one small umbrella that is far too small, all soaked, while the Charmander sits at their feet with an upturned plastic bucket over its head and its tail flame steaming in the rain, and the Pikachu sits inside Emma's jacket with only its face showing."),
# Video 2
("bo's first battle","Emma",G,"A dirt path through tall grass. Right in front of me, @Emma, blonde ponytail, denim jacket, points forward with a determined face, while her yellow Pikachu hides behind her leg, peeking around her knee with huge scared eyes. A few metres away on the path, a tiny green Caterpie the size of a hand sits looking at them. Nothing else moves."),
("he adopted it","Lukas",G,"A park bench by a pond. Right in front of me, @Lukas, grey hoodie with the hood up, is fast asleep lying on the bench, and lying on top of him, also fast asleep with its mouth open, is a fat pink Slowpoke with real smooth skin, its tail hanging off the bench into the pond. On the ground next to the bench, his yellow Psyduck sits holding its head, glaring at the Slowpoke with jealousy."),
("mira's birthday","Mira, Emma","with a warm cast from café lights","Inside a small café with wooden tables and fairy lights. Right in front of me, @Mira, red beanie, sits behind a small chocolate cake with one lit candle, staring straight into the camera with her dead-eyed face, while the round pink Jigglypuff has climbed onto the table and is sitting directly on top of the cake, puffed up with pride, cream on its feet. Next to her @Emma, blonde ponytail, is laughing with her head thrown back."),
("sam in the aquarium","Sam","with a cold blue cast from aquarium glass, dark","Inside a dark public aquarium in front of a huge glass tank glowing blue. Right in front of me, @Sam, black rain jacket, presses both hands and his face flat against the glass with an expression of pure love, while on the other side of the glass a gigantic blue Gyarados with real scales fills the whole tank, its huge eye level with Sam's face, staring back."),
("yuna's shopping list","Yuna, Sam","with a cold white cast from shop lights","Inside a small Poké Mart at the checkout. Right in front of me, @Yuna, yellow raincoat, stands with a shopping trolley piled dangerously high with at least forty purple potion bottles, holding a long crumpled list, while her small blue Squirtle sits on top of the pile. @Sam, black rain jacket, stands behind her in the queue holding one packet of fishing bait, looking at the pile."),
("rudi's bath day","Jonas","with a warm cast from a bathroom light, steamy","A small tiled bathroom full of steam. Right in front of me, @Jonas, red backwards cap, sleeves rolled up, holds his small orange Charmander in a sink full of foam with both hands, the Charmander holding its tail with the flame stiffly up out of the water, its face outraged, foam on its head. Water all over the floor, a scorched towel on the rail."),
("the ferry again","Lukas, Mira",G,"The open deck of the small rusty ferry on a grey sea. Right in front of me, @Lukas, grey hoodie, sleeps on a bench, and next to him his yellow Psyduck holds its head with its eyes glowing faintly blue, and this time every single object on the deck is floating, a bench, a bin, a bicycle, three bags, a seagull. @Mira, red beanie, stands among the floating objects with a coffee cup and a completely bored face, her hair floating upward."),
("gym number 2","Yuna, Emma",G,"The front of a large gym building with big double doors and a stone sign. Right in front of me, @Yuna, yellow raincoat, stands in front of the doors with her arms out in disbelief at a hand-written sign taped to the door, while her small blue Squirtle sits on the steps. Next to her @Emma, blonde ponytail, reads the sign with her hand over her mouth trying not to laugh. The sign is blurry and unreadable."),
("3 hours of this pt. 2","Lukas, Mira, Emma","with a warm cast from a reading light, blown-out window","Inside the old regional bus with worn blue seats and a rain-streaked window. In the row in front of me, @Lukas, grey hoodie, sleeps against the window with his mouth open, his yellow Psyduck asleep next to him holding its head, @Mira, red beanie, stares at the camera with a dead expression, and across the aisle @Emma, blonde ponytail, has fallen asleep too while her Pikachu quietly empties her open backpack of snacks."),
]
def build(items, tmpl):
    return [dict(n=i, title=t, attach=a, note=f"Video {1 if i<=9 else 2}", img=tmpl.format(cast=c, scene=s, caption=t)) for i,(t,a,c,s) in enumerate(items,1)]
WORLDS=[dict(key="hp",name="Wizarding World",clips=build(HP,HP_IMG)),dict(key="pk",name="Pokémon",clips=build(PK,PK_IMG))]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('snap-prompts.html',encoding='utf-8').read()
h=h.replace('<title>Snap Prompts</title>','<title>Snap Startframes 02</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
# nur Schritt 1
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – ${name.toUpperCase()} – STARTFRAMES (Batch 02, zwei Videos à 9 Clips)\nDie angehängten Referenz-Snaps sind die Stilvorlage für ALLE Bilder: gleiche Bildqualität, gleiche Farben, gleicher Caption-Balken. Alles ist ein echtes Handyfoto, nie Illustration, Anime, CGI oder Render. Die Figuren-Bilder bestimmen nur Gesicht, Haare und Kleidung der Person, nie den Bildstil.\nDie Figuren sind als Referenzbilder angehängt und werden mit @Name angesprochen (gleiche Person, gleiches Gesicht, gleiche Haare).\nNano Banana 2, 9:16. Pro Clip den BILD-Prompt eingeben, Stil-Referenzen und die genannten @Figuren anhängen, Ergebnis speichern. Die Video-Prompts kommen im zweiten Schritt, nachdem die Bilder fertig sind.\n`;", h, flags=re.S)
h=h.replace("function clipText(w,c){return `=== CLIP ${c.n}: ${c.title} ===\\nAnhängen: ${c.attach.split(',').map(a=>'@'+a.trim()).join(' ')}${c.note?` (${c.note})`:''}\\n\\n[SCHRITT 1 – BILD / STARTFRAME]\\n${c.img}\\n\\n[SCHRITT 2 – VIDEO, Startframe = Bild aus Schritt 1]\\n${c.vid}\\n`;}",
 "function clipText(w,c){return `=== ${c.note} · CLIP ${c.n}: ${c.title} ===\\nAnhängen: ${c.attach.split(',').map(a=>'@'+a.trim()).join(' ')}\\n\\n[BILD / STARTFRAME]\\n${c.img}\\n`;}")
assert 'SCHRITT 2 – VIDEO' not in h
h=h.replace('<button class="btn" data-all="${w.key}">Alle ${w.clips.length} Clips kopieren (mit Anleitung)</button><p>Ein Text für Flow: Anleitung oben (Referenz-Snaps als Stilvorlage, Figuren per @Name), dann je Clip Schritt 1 (Startframe mit Nano Banana 2) und Schritt 2 (Video mit Omni Flash 1.1, Startframe aus Schritt 1).</p>',
 '<button class="btn" data-all="${w.key}">Alle ${w.clips.length} Startframes kopieren (mit Anleitung)</button><p>Batch 02: zwei Videos à 9 Clips, nur Bild-Prompts. Bilder erzeugen, mir mit Clip-Nummer schicken, dann kommen die Video-Prompts.</p>')
# Video-Block aus der Karte entfernen
h=re.sub(r'\s*<div class="block"><div class="block-h"><span class="lab">Schritt 2 · Video \(10 s\)</span>.*?</button></div>', '', h, flags=re.S)
h=h.replace('<span class="lab">Schritt 1 · Bild / Startframe</span>','<span class="lab">Bild / Startframe</span>')
h=h.replace('<button class="mini primary" data-copy="both" data-w="${w.key}" data-n="${c.n}">Clip komplett kopieren (Schritt 1 + 2)</button>','')
h=h.replace("<div class=\"clip-head\"><span class=\"num\">${String(c.n).padStart(2,'0')}</span>","<div class=\"clip-head\"><span class=\"num\">${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}</span>")
h=h.replace("${c.note?`<span class=\"note\">${esc(c.note)}</span>`:''}","")
open('batch-02.html','w',encoding='utf-8').write(h)
print(len(WORLDS[0]['clips']),len(WORLDS[1]['clips']), 'vid' in h[:200])
