HP_IMG = ("Use the attached reference snaps as the style template: match their exact image quality, colours, framing and the look of the caption bar. A screenshot of a Snapchat snap from 2015, a real photo taken on an old iPhone 5 by a teenage student who raised the phone for one second. "
"The photo is out of focus and blurry: missed focus, motion blur, heavy sensor noise, strong JPEG compression with blocky artefacts, dull muted colours {cast}, "
"lifted milky blacks, no sharp details anywhere. Careless handheld framing, tilted, people cut off at the edges. Setting looks like the real film sets of a gothic "
"wizarding boarding school, students in black robes with white shirts, grey jumpers and striped house ties. {scene} Across the screen, slightly below the middle, "
"a Snapchat caption bar: a semi-transparent black rectangle at 60 percent opacity spanning the full width, with one line of small white Helvetica lowercase text, "
"centred, perfectly sharp, reading exactly: {caption}. Only the caption bar is sharp, the whole photo behind it is blurry. No other interface, no watermark, "
"no visible phone, no hands of mine in frame. Vertical 9:16, full-bleed.")
PK_IMG = ("Use the attached reference snaps as the style template: match their exact image quality, colours, framing and the look of the caption bar. A screenshot of a Snapchat snap from 2015, a real photo taken on an old iPhone 5 by a teenage trainer who raised the phone for one second. "
"The photo is out of focus and blurry: missed focus, motion blur, heavy sensor noise, strong JPEG compression with blocky artefacts, dull muted colours {cast}, "
"lifted milky blacks, no sharp details anywhere. Careless handheld framing, tilted, people cut off at the edges. Setting looks like the real live-action Pokémon world, "
"teenage trainers in caps, hoodies and backpacks, and Pokémon that look like real animals with real fur, scales and skin. {scene} Across the screen, slightly below the middle, "
"a Snapchat caption bar: a semi-transparent black rectangle at 60 percent opacity spanning the full width, with one line of small white Helvetica lowercase text, "
"centred, perfectly sharp, reading exactly: {caption}. Only the caption bar is sharp, the whole photo behind it is blurry. No other interface, no watermark, "
"no visible phone, no hands of mine in frame. Vertical 9:16, full-bleed.")
VID = ("Candid first-person video from my own eye level, as if I just raised my old iPhone and hit record {where}. 2015 smartphone video quality: soft focus, "
"visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a "
"phone microphone with {sounds}. The person holding the camera never speaks and makes no sound. All dialogue is spoken in casual, natural German. The Snapchat "
"caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. {body} Vertical 9:16. No watermark, "
"no visible phone or camera.")
W = "with a warm yellow cast from lamps and candles, blown-out windows and sky"
G = "with a cold grey cast, blown-out overcast sky"

HP = [
dict(title="he finally paid up", attach="Theo, Cara", cast=W,
 scene="Inside a crowded, cosy wooden pub with low beams, a roaring fire and steamed-up windows. Across a small wooden table from me, @Theo, green-silver tie, slides a foamy mug of butterbeer across the table with a sour face, while @Cara, blue scarf, grabs it with both hands and a huge triumphant grin. Two more mugs on the table.",
 where="at the pub table", sounds="a loud crowded pub, clinking mugs, a crackling fire",
 body="Crowded wooden pub, fire, steamed-up windows. Theo with the green-silver tie pushes the mug across the table with a sour face, Cara with the blue scarf grabs it grinning. Cara says: \"Drei Wochen. Drei Wochen hab ich gewartet.\" Theo says: \"Ihr habt nicht mal richtig gewonnen. Das war ein Unentschieden.\" Cara takes a huge gulp, foam on her nose, and says: \"Ein Unentschieden ist kein Verlieren. Also hab ich gewonnen.\" Theo looks at the camera with dead eyes and says: \"Sag ihr, dass das keine Logik ist.\" Cara slides the second mug toward the camera and says: \"Deins. Er zahlt für alle.\" Theo says: \"Ich zahle NICHT für alle.\" Cara raises her mug: \"Auf Theo!\" People at the next table cheer without knowing why. Theo puts his face in his hands. Warm firelight."),
dict(title="revision day 1", attach="Lena, Maja", cast="with a warm cast from green reading lamps, blown-out windows",
 scene="Old library with dark bookshelves and green lamps. At the table across from me, @Lena, red-gold tie, sits surrounded by a wall of open books and colour-coded notes, writing frantically, while next to her @Maja, blue-bronze tie, is fast asleep with her cheek flat on an open book and her mouth slightly open.",
 where="across the library table", sounds="library silence, a quill scratching fast, soft breathing",
 body="Library with green lamps. Lena writes frantically behind a wall of books, Maja sleeps with her cheek on a book. Lena whispers without looking up: \"Sie schläft seit vierzig Minuten. Auf Seite eins.\" Maja mumbles in her sleep: \"Ich lese mit geschlossenen Augen.\" Lena stops writing and stares at her: \"Du hast das Buch falsch herum.\" Maja, eyes still closed: \"Das ist eine Technik.\" Lena picks up a heavy book and drops it on the table with a bang. Maja jerks up, hair stuck to her cheek, looks around and says: \"Ich war wach. Was war die Frage?\" Lena says: \"Es gab keine Frage.\" Maja lays her head back down on the book and says: \"Dann weck mich, wenn es eine gibt.\" Lena looks at the camera and mouths: \"Hilfe.\" Warm lamplight."),
dict(title="it's his turn", attach="Finn", note="Originalfigur: der riesige Wildhüter", cast=G,
 scene="A muddy paddock at the edge of a dark forest with a wooden fence, the castle far away. A group of students in robes stands in a nervous semicircle. In the middle, @Finn, yellow-black tie, stands alone a few steps in front of the others with his shoulders up and a terrified face, looking back at the camera. In front of him, a huge grey creature with the body of a horse and the head and wings of an eagle stands in the mud, half out of focus, staring at him.",
 where="at the paddock fence", sounds="wind, nervous whispering, a big animal snorting and heavy boots in mud",
 body="Muddy paddock by the forest. Finn with the yellow-black tie stands alone in front of the huge grey eagle-headed horse creature, looking back at the camera in terror. From the right, an enormous, broad man with a wild tangle of black hair and a huge bushy black beard in a giant brown moleskin overcoat stomps into frame and booms cheerfully: \"Na los, Junge! Verbeugen! Und nicht blinzeln, das mögen sie nicht!\" Finn whispers: \"Was, wenn es sich nicht verbeugt?\" The giant man says: \"Dann rennst du.\" Finn bows stiffly, the creature stares, the whole class holds its breath, and then the creature slowly bends one front leg and bows back. The class cheers. Finn straightens up, turns to the camera with a shaky grin and says: \"Ich lebe!\" The creature's beak nudges him hard from behind, he stumbles forward into the mud face-first, and the giant man roars with laughter: \"Der mag dich!\" Grey overcast light."),
dict(title="he found the kitchen", attach="Ollie", cast="with a warm orange cast from fires",
 scene="A huge vaulted stone kitchen with copper pots, four long tables, brick fireplaces and stacks of pies and cakes. Right in front of me, @Ollie, yellow-black tie, sits on a table with a whole pie in his lap and cream on his face, holding a second one, looking at the camera with wide happy eyes. Several small, big-eared, big-eyed creatures in tea-towel togas stand around him, out of focus, holding more plates.",
 where="in the kitchen doorway", sounds="clattering pots, crackling fires and lots of small squeaky voices",
 body="Vaulted stone kitchen with copper pots and fireplaces. Ollie with the yellow-black tie sits on the table with a pie in his lap and cream on his face, small big-eared creatures in tea towels around him. Ollie says with his mouth full: \"Es ist direkt neben unserem Gemeinschaftsraum. DIREKT daneben. Seit drei Jahren.\" A small creature squeaks: \"Möchte der junge Herr noch Pudding?\" Ollie says: \"Ja.\" Another squeaks: \"Und Kuchen?\" Ollie says: \"Ja.\" A third holds up a whole roast chicken and Ollie says, almost crying: \"Ja.\" He looks at the camera and says: \"Ich gehe nie wieder in die Große Halle.\" A tall creature with a stern face pushes through, looks at the camera and says: \"Der junge Herr darf nicht filmen.\" Ollie says: \"Er darf alles, er ist mit mir.\" The stern creature snaps its fingers and a plate of biscuits appears in front of the camera. Warm orange firelight."),
dict(title="she predicted my death again", attach="Nova, Maja", note="Originalfigur: die Wahrsage-Lehrerin", cast="with a hazy pink-orange cast from incense and lamps",
 scene="A cramped round tower classroom stuffed with armchairs, tasselled lamps, teacups and crystal balls, thick with incense smoke. At a small round table right in front of me, @Nova, green-silver tie, stares flatly into the camera with a teacup in front of her, while @Maja, blue-bronze tie, next to her peers into a crystal ball with her nose almost touching it.",
 where="at the table", sounds="a quiet stuffy room, clinking teacups and a breathy dramatic voice",
 body="Smoky round tower classroom with armchairs and crystal balls. Nova stares at the camera, Maja peers into the crystal ball. A thin, birdlike woman with huge thick glasses that magnify her eyes, wild frizzy hair, layers of shawls, beads and bangles drifts to the table, snatches Nova's teacup, peers into it and gasps: \"Oh, mein armes Kind. Der Grimm. Der Tod. Noch vor dem Wochenende.\" Nova, without blinking: \"Das haben Sie letzte Woche auch gesagt.\" The teacher whispers: \"Das Schicksal ist geduldig.\" Maja looks up from the crystal ball and says dreamily: \"Ich seh einen Hund. Oder eine Wolke. Oder Kartoffelbrei.\" The teacher clutches her chest: \"Ein Hund! Der Grimm!\" Nova takes her cup back, drinks the tea in one go, puts it down and says: \"Jetzt ist er weg.\" The teacher stares at her in horror, Maja says: \"Doch, Kartoffelbrei\", and the teacher drifts away moaning. Nova looks at the camera and says: \"Nächste Woche wieder.\" Hazy pink light, incense drifting."),
dict(title="slytherin common room tour", attach="Theo, Nova", cast="with a cold green cast from underwater light",
 scene="A long low dungeon common room with green leather sofas, stone pillars, hanging green lamps and tall windows into dark green lake water with a shadow of something huge drifting past. Right in front of me, @Theo, green-silver tie, spreads his arms proudly like a tour guide, while @Nova, green-silver tie, sits on the sofa behind him on her phone, ignoring everything.",
 where="in the dungeon common room", sounds="a low echoing room, muffled water sounds and a fire crackling",
 body="Green-lit dungeon common room with lake windows. Theo spreads his arms and says: \"Willkommen. Bester Gemeinschaftsraum der Schule. Unter dem See. Fenster direkt ins Wasser.\" He points at the window, a huge dark shadow with tentacles drifts past behind the glass, and he says: \"Das ist der Kraken. Der heißt Gerald.\" Nova, without looking up from her phone: \"Der heißt nicht Gerald.\" Theo: \"Ich nenne ihn Gerald.\" Nova: \"Er hat letzte Woche Finns Schuh gefressen.\" Theo: \"Finn hätte den Schuh nicht ins Wasser halten sollen.\" The shadow presses one giant eye against the glass, Theo jumps back, then pretends he didn't. Nova finally looks up, looks at the camera and says flatly: \"Es ist kalt, es ist nass, es riecht nach Fisch. Tour beendet.\" Theo says: \"Sie liebt es hier.\" Cold green light."),
dict(title="don't buy from them", attach="Cara, Finn", note="Originalfiguren: die Zwillinge", cast=W,
 scene="A busy stone corridor with a makeshift stall made of a trunk covered in colourful sweets, boxes and fireworks, a crowd of younger students around it. Right in front of me, @Cara, blue scarf, holds up a bright purple sweet with a suspicious face, while @Finn, yellow-black tie, next to her has just eaten one and his face is turning bright orange with steam coming out of his ears. Behind the stall, two tall boys with identical faces and matching red hair are out of focus, grinning.",
 where="in the corridor", sounds="a noisy corridor, kids laughing, a small firework popping",
 body="Busy corridor, sweet stall on a trunk. Cara holds a purple sweet, Finn's face is bright orange with steam out of his ears. Behind the stall, two tall identical boys with matching red hair and matching grins lean forward. The first says: \"Vollkommen harmlos.\" The second says: \"Geht in zehn Minuten weg.\" The first: \"Meistens.\" Finn, with steam coming out of his ears, says: \"MEISTENS?\" Cara says: \"Was ist in dem lila?\" The twins say in unison: \"Überraschung.\" Cara eats it. Nothing happens. She says: \"Und?\" Then her hair slowly stands straight up in the air and turns bright blue. Finn laughs so hard the steam whistles. The twins high-five, the first says: \"Zwei Sickel\", the second holds out his hand to the camera: \"Und für dich haben wir was ganz Besonderes.\" Cara grabs the camera hand and pulls me away, shouting: \"Nicht! Nicht kaufen!\" Warm candlelight."),
dict(title="she's crying again", attach="Lena", note="Originalfigur: das Geistermädchen", cast="with a cold grey-blue cast",
 scene="A gloomy old stone bathroom with a row of cracked sinks, wooden stalls with the doors hanging open and water all over the floor. Right in front of me, @Lena, red-gold tie, stands at a sink with wet shoes and her arms full of books, looking at the camera with a tired \"not again\" face. Behind her, the last stall is glowing faintly silver-white and a loud wail seems to be coming from it.",
 where="in the bathroom doorway", sounds="dripping water, an echoing tiled room and loud sobbing",
 body="Gloomy stone bathroom, water on the floor. Lena stands at the sink with her books, tired. Out of the glowing stall floats a translucent, silvery ghost of a teenage girl with pigtails, thick round glasses and a school uniform, sobbing loudly, and hovers right in front of Lena. The ghost wails: \"Ihr kommt alle nur her, wenn ihr mich braucht! Niemand kommt einfach so!\" Lena says: \"Ich muss nur Hände waschen.\" The ghost sobs harder: \"HÄNDE WASCHEN. Natürlich. In MEINEM Klo.\" Lena: \"Es ist ein Schulklo.\" The ghost shrieks, dives head-first into the nearest toilet, and a wave of water shoots up and out of the bowl all over the floor and Lena's shoes. Lena closes her eyes, breathes in, and says very quietly: \"Zweites Paar Schuhe diese Woche.\" From inside the pipes the ghost's voice echoes: \"Das hast du dir selbst zuzuschreiben!\" Lena looks at the camera and says: \"Ich geh auf ein anderes Klo.\" Cold grey light."),
dict(title="he's talking about the forest again", attach="Maja, Ollie", note="Originalfigur: der Schulleiter", cast="with a warm yellow cast from hundreds of candles, blown-out windows",
 scene="Vast candlelit dining hall with long tables full of students, seen from my seat. Right in front of me across the table, @Maja, blue-bronze tie, rests her chin on both hands staring blankly toward the front, and @Ollie, yellow-black tie, next to her is asleep sitting up with his head tipped back. Far away at the front of the hall, out of focus, an old man with a very long silver beard stands at a golden lectern with his arms spread.",
 where="from my seat", sounds="a huge hall, distant echoing speech, whispering and a soft snore",
 body="Candlelit dining hall. Maja stares blankly toward the front, Ollie sleeps sitting up. Far away, the old man with the very long silver beard, half-moon spectacles and long purple robes speaks slowly at the golden lectern, his voice echoing: \"...und der Wald bleibt, wie in jedem Jahr, für alle Schüler verboten. Für alle. Auch für die, die glauben, ich sehe sie nicht.\" Maja whispers without moving: \"Er guckt zu uns.\" Ollie snores. The old man pauses and says: \"Und wer im Wald etwas verloren hat, darf es nicht holen. Auch keinen Schuh.\" Maja whispers: \"Er meint Finn.\" Ollie mumbles in his sleep: \"Wo ist mein Pudding.\" The old man says: \"Nun, guten Appetit\", claps once, food appears on the tables, and Ollie's eyes snap open instantly. He grabs a chicken leg and says: \"Was hab ich verpasst?\" Maja says: \"Nichts. Wald. Verboten.\" Ollie: \"Wieder?\" Warm candlelight."),
]

HP_ORIG = [
dict(title="he's coming over. don't.", attach="Theo", note="Originalfigur: der blonde Junge", cast="with a warm yellow cast from the shop lamps, blown-out white sky",
 scene="Snowy cobblestone village street at dusk with crooked half-timbered shops, warm glowing windows and a hanging wooden pub sign, a crowd of students behind. Very close on the left, cropped at the shoulder, @Theo, green-silver tie, holds a mug of foamy butterbeer and rolls his eyes at me. The right half of the frame is open street with students walking in the distance.",
 where="in the street", sounds="crowd chatter, boots on snow and wind",
 body="Snowy village street at dusk with glowing shop windows and a hanging pub sign, students in black robes walking behind. On the left, close, Theo with the green-silver tie holds his butterbeer and rolls his eyes. From the right, a pale, thin boy with slicked-back platinum blond hair, sharp pointed features and a permanent sneer, black robe with green lining and green-silver striped tie, walks into the frame flanked by two big, dumb-looking boys in black robes, and stops right next to us. He looks at the butterbeer, then at Theo, and says in a slow, drawling voice: \"Butterbier. Wie süß. Trinkt ihr das mit Strohhalm?\" Theo says without looking at him: \"Willst du auch eins, oder hast du dein Taschengeld schon für Haargel ausgegeben?\" The two big boys snort, the blond boy shoots them a look and they go quiet. He sneers at the camera, says: \"Filmst du mich? Mein Vater wird davon hören\", and walks off with the two boys behind him. Theo watches him go, takes a sip and says: \"Jedes Mal. Jedes einzelne Mal.\" Overcast winter light with warm lantern glow."),
dict(title="he gave up", attach="Finn", note="Originalfigur: die strenge Lehrerin", cast="with a warm cast from candles, blown-out windows",
 scene="Vast stone stairwell with walls full of gold-framed portraits, candles and tall windows. On the landing right in front of me, @Finn, yellow-black tie, sits on the bottom step of a staircase with his head in his hands, his bag spilled open with books all over the steps, a couple of other students stepping around him. The top of the staircase behind him is empty.",
 where="on the landing", sounds="echoing footsteps and voices in a huge stone stairwell",
 body="Stone stairwell with portraits and candles. Finn with the yellow-black tie sits on the bottom step with his head in his hands, books all over the steps. Sharp, fast footsteps echo from above, students scatter, and a tall, thin, stern older witch in long emerald green robes and a tall pointed black hat, with a tight grey bun, square spectacles and thin pressed lips, sweeps down the staircase behind him, stops right above him and looks down over her glasses. She says crisply: \"Mister, dies ist eine Treppe und kein Wartezimmer.\" Finn looks up, sees her, and scrambles to his feet, stepping on his own books. He says: \"Die Treppe ist weggefahren, Professor, ich konnte nicht...\" She says: \"Die Treppe fährt seit siebenhundert Jahren weg. Man rechnet damit.\" She flicks her wand, the books fly into his bag in a neat stack, and she walks past him and past the camera without slowing down, saying: \"Fünf Punkte Abzug für das Sitzen. Und sagen Sie Ihrer Freundin, sie soll das Telefon wegstecken.\" Finn stares after her, then at the camera, and whispers: \"Sie hat dich gesehen.\" Cold light from the windows, candle flames flickering."),
dict(title="detention but make it pumpkins", attach="Maja, Lena", note="Originalfigur: der Riese", cast=G,
 scene="A muddy pumpkin patch with huge pumpkins next to a round stone hut with a smoking chimney, a dark forest behind, the castle far away on the hill. Right in front of me, @Maja, blue-bronze tie, sits on a giant pumpkin eating an apple, and @Lena, red-gold tie, stands next to her with muddy hands holding a bucket, looking at me exhausted. The door of the hut behind them is open and dark.",
 where="at the pumpkin patch", sounds="wind, crows, a bucket clanking and a big dog barking somewhere",
 body="Muddy pumpkin patch by a round stone hut, forest behind. Maja sits on a giant pumpkin eating an apple, Lena stands with a bucket and muddy hands. Lena says: \"Du hast noch keinen einzigen Kürbis angefasst.\" Maja says with her mouth full: \"Ich bewache sie.\" Heavy footsteps thud, the ground shakes slightly, and out of the hut door ducks an enormous, broad man with a wild tangle of black hair and a huge bushy black beard, in a giant brown moleskin overcoat, carrying a bucket the size of a barrel, followed by a massive slobbering black boarhound. He booms cheerfully: \"Na, ihr zwei! Die Kürbisse wachsen nicht schneller, wenn man sie anguckt!\" The dog bounds over, jumps up at Maja and licks her face, she shrieks and drops the apple. The giant man laughs: \"Der mag dich! Er mag nur die Faulen.\" Lena laughs so hard she drops the bucket. The man sets his huge bucket down with a thud in front of the camera and says: \"Und du, das Ding weg. Die Kürbisse mögen keine Fotos.\" The dog eats the apple. Grey overcast light."),
dict(title="kitchen run gone wrong", attach="Nova, Ollie", note="Originalfigur: der Hausmeister", cast="with a cold blue cast from moonlight, extremely dark",
 scene="A long dark stone corridor at night with arched windows letting in moonlight, suits of armour along the wall. Right in front of me, @Nova, green-silver tie, stands flat against the wall with a finger to her lips, and @Ollie, yellow-black tie, crouches next to her eating a pastry, crumbs on his jumper. The far end of the corridor is pitch black.",
 where="in the dark corridor", sounds="near silence, chewing, a distant door and slow shuffling footsteps",
 body="Dark stone corridor at night, moonlight through arched windows, suits of armour. Nova stands against the wall with her finger to her lips, Ollie crouches and eats a pastry. Ollie whispers with his mouth full: \"Willst du auch? Ich hab sechs.\" Nova whispers: \"Halt die Klappe.\" A faint lantern glow appears at the far end of the corridor, growing, and a scruffy grey cat with lamp-like eyes trots out of the dark and stops, staring at us. Behind it shuffles a hunched, gaunt old man in a long shabby brown coat with greasy grey hair, sunken cheeks and a sour face, holding up an oil lantern. He rasps: \"Schüler. Nach der Sperrstunde. Wunderbar.\" Ollie freezes with the pastry in his mouth. Nova says flatly, without moving: \"Wir sind Rüstungen.\" The old man shuffles closer, holds the lantern up to her face, and says: \"Rüstungen essen keine Pasteten.\" Ollie swallows and whispers: \"Ich hab sechs, wollen Sie eine?\" The old man's face twitches, the cat hisses, and he grabs both of them by the collar and marches them past the camera, saying: \"Der Hausmeister will euch sehen. Beide. Und das Ding da auch.\" The camera jerks and drops toward the floor. Cold blue moonlight."),
dict(title="she has opinions about the keeper", attach="Cara", note="Originalfigur: das seltsame Mädchen", cast="with a warm yellow cast from candles, blown-out windows",
 scene="Vast candlelit dining hall with long wooden tables, golden goblets and plates of food. Right across the table from me, @Cara, blue-bronze tie, is mid-rant with a fork in the air, a plate of pudding in front of her. The seat next to her is empty, a folded magazine lying on the bench.",
 where="across the table", sounds="the echoing chatter of a huge hall, cutlery and benches scraping",
 body="Candlelit dining hall, long tables full of students. Cara with the blue-bronze tie waves her fork and says: \"Und dann lässt er den dritten durch. Den DRITTEN. Ich hätte den mit den Augen zu gehalten.\" A girl with long, wavy, very pale blonde hair, large dreamy pale eyes, a blue-bronze tie, radish-shaped earrings and a necklace of corks sits down on the empty seat next to her, picks up the magazine, opens it upside down and starts reading. Without looking up she says in a soft, airy, faraway voice: \"Er hatte Wrackspurts im Kopf. Die machen das Hirn ganz neblig. Deshalb konnte er nichts sehen.\" Cara stops mid-rant, fork still in the air, and stares at her. She says: \"...Was?\" The blonde girl turns a page, still upside down, and says: \"Ich kann ihm eine Brille leihen. Aber die Wrackspurts fliegen nur raus, wenn man Glück hat.\" Cara looks at the camera with her mouth open, then slowly puts the fork down and says: \"Okay. Okay, ja.\" The blonde girl takes a spoon of Cara's pudding, eats it, and says happily: \"Der ist heute besonders gut.\" Warm candlelight."),
]

PK = [
dict(title="we said no fire", attach="Jonas, Mira", cast="with a warm orange cast from fire, dark night",
 scene="A forest campsite at night. A small green tent is burning at one corner with a bright flame, sparks flying up. Next to it, @Jonas, red backwards cap, green hoodie, stands with his hands in his pockets watching calmly, while his small orange Charmander sits at his feet looking guilty with its tail flame flickering. @Mira, red beanie, sits on a log with a sleeping bag around her shoulders staring at the camera with a dead expression.",
 where="at the campsite", sounds="crackling fire, crickets and wind in the trees",
 body="Forest campsite at night. The tent corner burns, Jonas watches with his hands in his pockets, the Charmander sits guilty at his feet, Mira sits on the log in her sleeping bag. Mira says flatly: \"Das ist dein Zelt.\" Jonas says: \"Ich weiß.\" Mira: \"Wo schläfst du jetzt?\" Jonas: \"In deinem.\" Mira: \"Nein.\" The flame spreads up the tent pole, the Charmander looks up at Jonas and says a small worried \"glu\". Jonas looks down at it and says: \"Rudi. Was hab ich gesagt?\" The Charmander looks at the fire, then at Jonas, then wags its tail and the flame on its tail flares up brighter. Mira says: \"Es versteht dich nicht.\" Jonas says: \"Es versteht mich. Es ist ihm egal.\" The tent collapses in a shower of sparks, Mira pulls her sleeping bag over her head, and Jonas sits down on the log next to her and says: \"Ist eh warm jetzt.\" Orange firelight."),
dict(title="we got kicked out", attach="Emma", cast="with a cold white cast from shop lights",
 scene="Inside a small blue-roofed Poké Mart with shelves of potions, berries and Poké Balls. Right in front of me, @Emma, blonde ponytail, denim jacket, stands at the checkout with a red face holding out a coin purse, while her yellow Pikachu sits inside the shopping basket on the counter surrounded by torn-open berry packets, cheeks stuffed, looking innocent. A shop clerk in a blue apron stands behind the counter with folded arms, out of focus.",
 where="at the checkout", sounds="a beeping till, shop music and crinkling packets",
 body="Small Poké Mart checkout. Emma holds out her coin purse red-faced, the Pikachu sits in the basket among torn berry packets, the clerk stands with folded arms. The clerk says: \"Vierzehn Packungen. Vierzehn.\" Emma says: \"Ich zahle alles. Alles. Er hatte Hunger.\" The Pikachu reaches for another packet on the counter, Emma slaps its paw away, it looks at her offended and says \"pika\" with a full mouth. The clerk says: \"Und die Trinkflasche.\" Emma: \"Welche Trinkflasche?\" The Pikachu slowly lifts a half-empty bottle out of the basket. Emma closes her eyes and says: \"Bo. Ich schwöre.\" The clerk points at the door and says: \"Bezahlen. Und dann bitte raus. Mit dem Ding.\" Emma picks up the basket, the Pikachu grabs one last packet on the way, and she says to the camera: \"Sag nichts. Sag einfach nichts.\" Cold shop light."),
dict(title="it's happening", attach="Lukas, Mira", cast=G,
 scene="The open deck of a small rusty ferry on a grey sea, wet metal benches. On a bench right in front of me, @Lukas, grey hoodie with the hood up, is asleep leaning sideways, and next to him his yellow Psyduck sits holding its head with both hands, its eyes glowing faint blue and every loose object on the deck, a cup, a hat, a life ring, floating slightly in the air around it. @Mira, red beanie, stands behind the bench looking at the camera with a dead face and one eyebrow raised.",
 where="on the ferry deck", sounds="wind, engine rumble, seagulls and a low humming",
 body="Ferry deck on a grey sea. Lukas sleeps on the bench, the Psyduck holds its head with glowing eyes, a cup, a hat and a life ring float around it, Mira stands behind. Mira says: \"Lukas.\" No reaction. She says louder: \"Lukas. Dein Enton.\" Lukas mumbles with his eyes shut: \"Sind wir da?\" The humming gets louder, the bench starts to lift a few centimetres off the deck with Lukas on it. Mira says: \"Nein, aber du schwebst.\" Lukas opens one eye, looks down, closes it again and says: \"Dann weck mich, wenn wir landen.\" A seagull flies past, gets caught in the glow and hovers in mid-air, flapping in confusion. Mira looks at the seagull, then at the camera, and says: \"Ich hab gesagt, wir nehmen den Bus.\" The Psyduck lets out a long \"psy\", everything drops at once, the bench bangs down, the cup rolls across the deck and Lukas says: \"Was war das?\" Mira says: \"Nichts. Schlaf weiter.\" Grey sea light."),
dict(title="progress", attach="Sam, Emma", cast=G,
 scene="A muddy riverbank with reeds and a wooden bridge behind. Right in front of me, @Sam, black rain jacket, holds up his fishing rod with an old rubber boot dangling from the hook, water pouring out of it, and grins at the camera proudly. Next to him, @Emma, blonde ponytail, denim jacket, stares at the boot, her Pikachu on her shoulder also staring at the boot.",
 where="on the riverbank", sounds="a flowing river, wind in the reeds and water dripping",
 body="Muddy riverbank with reeds and a bridge. Sam holds up the rod with the dripping boot, grinning. Emma and her Pikachu stare at it. Sam says: \"Kein Karpador!\" Emma says: \"Das ist ein Stiefel.\" Sam: \"Ja, aber kein Karpador. Das ist Fortschritt.\" The boot swings, water pours out, and a tiny orange Magikarp flops out of the boot onto the mud. Sam looks down at it, his grin fades, and he says quietly: \"Nein.\" The Magikarp flops toward the water. Emma starts laughing, the Pikachu laughs with its mouth open. Sam drops the rod and dives for the Magikarp, misses, and slides face-first into the mud as it splashes into the river. He lies there and says into the mud: \"Das zählt nicht.\" Emma, wiping her eyes: \"Das zählt total.\" The Pikachu picks up the boot and puts it on its head. Grey overcast light."),
dict(title="she's been here since 6", attach="Yuna", cast="with a cold blue cast of early morning, blown-out sky",
 scene="A small-town square at dawn with a stone fountain, closed shops and empty benches. In the middle of the square, @Yuna, yellow raincoat, stands with her arm out pointing at the fountain, her small blue Squirtle in the fountain basin spraying a jet of water at a plastic bottle set up on the rim. Empty energy drink cans and a stopwatch on the bench in the foreground.",
 where="from the bench", sounds="splashing water, birds, a distant shop shutter opening",
 body="Town square at dawn with a fountain. Yuna points, the Squirtle sprays water at a plastic bottle on the fountain rim. Yuna shouts: \"Nochmal! Fester!\" The Squirtle sprays, the bottle wobbles and stays standing. Yuna: \"Nochmal!\" The Squirtle sprays again, the bottle falls over, and Yuna throws both arms up and screams \"JA!\" so loud that a flock of pigeons bursts off the fountain. The Squirtle climbs out of the basin, lies flat on its back on the ground and stares at the sky, exhausted. Yuna sets the bottle back up and says: \"Gut. Jetzt von weiter weg.\" The Squirtle doesn't move. Yuna: \"Kai. Aufstehen.\" The Squirtle slowly pulls its head into its shell. An old man opening his shop across the square calls: \"Es ist halb sieben!\" Yuna calls back: \"Ich weiß!\" and turns to the camera: \"Er ist fast so weit.\" Cold blue morning light."),
dict(title="it chose her", attach="Mira", cast=G,
 scene="A quiet suburban street with hedges and lamp posts. Right in front of me, @Mira, red beanie, navy rain jacket, walks away from the camera down the pavement with her hands in her pockets, looking back over her shoulder with an annoyed dead-eyed face, and a round pink furry Jigglypuff waddles along the pavement a few steps behind her, following her.",
 where="while walking behind them", sounds="footsteps on pavement, wind, a car passing and small soft footsteps",
 body="Quiet suburban street. Mira walks ahead, looking back annoyed, the Jigglypuff waddling behind her. Mira stops. The Jigglypuff stops. Mira says without turning around: \"Geh nach Hause.\" The Jigglypuff says \"puff\". Mira walks on, the Jigglypuff walks on. Mira stops again, turns around and says: \"Ich will kein Pokémon. Ich hab das zehnmal gesagt.\" The Jigglypuff looks up at her with huge shiny eyes and takes a deep breath, puffing up. Mira points at it and says sharply: \"Nicht singen.\" The Jigglypuff deflates slowly with a squeak. Mira turns to the camera and says: \"Warum ich. Es gibt hundert Leute in dieser Stadt.\" The Jigglypuff waddles up, hugs her leg, and holds on. Mira looks down at it for a long moment, sighs, and keeps walking with the Jigglypuff still hanging on her leg, dragging it along. She says: \"Es heißt nicht Pummel.\" The Jigglypuff says \"puff\" happily. Grey overcast light."),
dict(title="day 5", attach="Jonas, Lukas", cast="with a cold cast, blown-out misty sky",
 scene="The same narrow misty country road between trees and a wooden fence. The gigantic dark teal Snorlax still lies across the road, asleep, but now there is a small tent pitched against its belly, a washing line with socks tied from its ear to the fence, and a camping stove on the road. @Jonas, red backwards cap, lies on top of the Snorlax's belly like a sunbed with his arms behind his head, and @Lukas, grey hoodie, is asleep in the tent doorway with his Psyduck sitting next to him holding its head.",
 where="on the road", sounds="birds, a camping stove hissing and a deep slow snore",
 body="Misty road, Snorlax with a tent against its belly and a washing line from its ear. Jonas lies on the belly, Lukas sleeps in the tent doorway with the Psyduck. Jonas says lazily: \"Ehrlich, ich will gar nicht mehr, dass es aufwacht.\" Lukas says with his eyes closed: \"Ich auch nicht.\" Jonas: \"Hier ist es schön. Ruhig. Warm.\" The Snorlax snores, the belly rises and Jonas rises with it. Lukas: \"Was ist mit der Arena?\" Jonas: \"Die Arena läuft nicht weg.\" Lukas: \"Yuna wartet seit fünf Tagen.\" Jonas: \"Yuna kämpft eh vierzig Minuten pro Runde.\" A cyclist appears in the mist, stops in front of the Snorlax, looks at it, looks at the tent, and says: \"Ist das... seit wann ist das hier?\" Jonas, without lifting his head: \"Dienstag.\" The cyclist turns around and rides back. Lukas mumbles: \"Netter Typ.\" The Psyduck lets out a small \"psy\". Misty grey light."),
dict(title="she actually won", attach="Yuna, Emma, Sam", cast="with a cold cast from stadium lights",
 scene="The dusty stone gym arena with white lines and wooden bleachers. Right in front of me on the arena floor, @Yuna, yellow raincoat, holds up a small shiny grey badge with both hands and an insane wide-eyed grin, her Squirtle collapsed on its back at her feet. @Emma, blonde ponytail, and @Sam, black rain jacket, are running toward her from the side, blurred, arms in the air.",
 where="on the arena floor", sounds="a cheering crowd, echoing hall and screaming",
 body="Dusty gym arena. Yuna holds up the badge grinning, the Squirtle lies on its back, Emma and Sam run in. Yuna screams: \"EINE STUNDE ZWÖLF! Eine Stunde zwölf Minuten!\" Emma reaches her and hugs her so hard the badge flies out of her hand, Sam catches it, looks at it and says: \"Der ist echt klein.\" Yuna grabs it back: \"Das ist ein ORDEN.\" Emma says: \"Wir dachten, du stirbst da drin.\" Yuna: \"Ich auch!\" Sam crouches next to the Squirtle, pokes it, and it doesn't move. Sam says: \"Kai ist tot.\" Yuna says: \"Kai schläft.\" The Squirtle lifts one arm weakly and lets it drop. Emma: \"Kai schläft.\" Yuna holds the badge up to the camera and says: \"Der nächste ist in drei Tagen. Wir gehen JETZT los.\" Emma and Sam say at the same time: \"Nein.\" Cold stadium light."),
dict(title="3am at the pokecenter", attach="Jonas, Emma", cast="with a cold greenish cast from a humming ceiling light, dark",
 scene="The Pokémon Center waiting room at night, mostly dark, one flickering ceiling light, a vending machine glowing. @Jonas, red cap over his face, lies across three plastic chairs asleep, his Charmander curled up on his chest with its tail flame lighting his hoodie. @Emma, blonde ponytail, sits on the floor against the vending machine with her eyes closed while her Pikachu is halfway inside the vending machine flap pulling out a snack. A sleeping Psyduck sits on a chair in the background holding its head.",
 where="from a chair in the dark waiting room", sounds="a humming, flickering light, a vending machine buzzing, soft snoring and a crinkling packet",
 body="Dark Pokémon Center waiting room. Jonas sleeps across the chairs with the Charmander on his chest, Emma sits against the vending machine with her eyes closed, the Pikachu is halfway inside the flap. The Pikachu wriggles, a packet drops, it pulls its head out with the packet in its mouth and looks straight at the camera, frozen. Emma says with her eyes closed: \"Bo. Leg das zurück.\" The Pikachu slowly puts the packet back into the flap. Emma: \"Das andere auch.\" The Pikachu slowly pulls a second packet out of its cheek pouch and puts it back. The Charmander's tail flame flares, a corner of Jonas's hoodie starts to smoulder, and Jonas says from under his cap, without moving: \"Rudi.\" The flame goes down. Emma opens one eye, looks at the smoke, and says: \"Wenn das hier abbrennt, schlafen wir draußen.\" Jonas: \"Draußen ist das Relaxo.\" Emma: \"Dann auf dem Relaxo.\" The Psyduck in the background lets out a small \"psy\" in its sleep and the ceiling light flickers off, then on again. Jonas says: \"Herbert, nicht jetzt.\" Cold flickering light."),
]

def build(items, tmpl):
    out=[]
    for i,d in enumerate(items,1):
        out.append(dict(n=i, title=d['title'], attach=d['attach'], note=d.get('note',''),
            img=tmpl.format(cast=d['cast'], scene=d['scene'], caption=d['title']),
            vid=VID.format(where=d['where'], sounds=d['sounds'], body=d['body'])))
    return out
WORLDS = [
 dict(key="hp", name="Wizarding World", clips=build(HP, HP_IMG)),
 dict(key="pk", name="Pokémon", clips=build(PK, PK_IMG)),
]
