import json, re
Q="2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with "
N="The person holding the camera never speaks and makes no sound. "
L="All dialogue is spoken in English with natural British accents, casual teenage talk. The Snapchat caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. "
V=[
("she said 20 minutes. it's been 3 hours",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the rug in the common room and hit record. "+Q+"a crackling fire, pages turning and two boys chatting quietly behind. "+N+"The only people who speak are the girl lying on the rug and the boy in the armchair behind her, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A blue and bronze common room at night with a fire, a starry ceiling and bookshelves. A girl with long dark hair in a grey jumper lies flat on her stomach on the rug with her head propped on one hand and her eyes closed, a stack of books beside her. Behind her two boys sit in armchairs. My hand holding a phone is blurred at the edge of the frame. For the first two seconds she does not move at all, only her fingers twitch, as if she heard me. Then she opens one eye, looks at the camera and says with lips moving: \"I'm not asleep. I'm thinking.\" She listens for two seconds as if I'm answering, closes the eye again and mumbles: \"Five more minutes.\" The boy in the armchair leans forward into frame, looks at the camera and says: \"She said that at seven.\" She rolls onto her back, pulls her arm over her face and says: \"Twenty. I said twenty.\" The boy laughs and leans back out of frame. Two seconds pass with her lying there, one hand waving me away. Warm firelight, dark corners. Vertical 9:16. No watermark, no visible phone or camera."),
("do not buy anything from them",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the sofa in the common room and hit record. "+Q+"a roaring fire, cardboard boxes rattling and two identical laughs. "+N+"The only people who speak are the two ginger twins at the table, and each turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A warm red common room at night, a fire, a low table covered in colourful sweet boxes and wrappers. Two identical teenage boys with ginger hair, grey jumpers and red-gold ties sit on the far side of the table grinning, one holding a box, the other unwrapping something. The back of a boy's head is blurred on the left, my knee is blurred at the bottom. For the first two seconds the twins keep grinning at each other and one shakes a box next to his ear. Then the twin on the left turns to the camera, holds up the box and says with lips moving: \"Two sickles. Completely safe.\" The twin on the right leans in and says: \"Mostly safe.\" They listen for two seconds as if I'm answering. Then the left twin slides a purple sweet across the table toward the lens and says: \"Free sample. Go on.\" The right twin, grinning wider: \"Tell us if your ears go.\" The boy with his back to me shakes his head and pushes the sweet back. The twins burst out laughing and the camera dips as I lean away. Warm orange firelight. Vertical 9:16. No watermark, no visible phone or camera."),
("ravenclaw won. pay up",
"Candid first-person video from my own eye level, as if I just raised my old iPhone across the pub table and hit record. "+Q+"a noisy pub, mugs knocking on wood, chatter and laughter all around. "+N+"The only person who speaks is the pale boy with slicked blond hair, and he faces the camera when speaking so his lips are visible moving with every word. "+L+
"A dark wooden pub full of students in black robes, oil lamps on the walls, a scratched table with several mugs of butterbeer. Across the table a pale teenage boy with slicked-back white-blond hair, a green-silver tie and black robes glares straight into the camera with a sour face, one hand reaching for a mug. My finger is blurred over the bottom corner of the lens. For the first two seconds my finger slides off the lens and he keeps glaring, hand frozen on the mug, as if waiting for me to stop talking. Then he says with lips moving: \"It doesn't count. Your seeker got lucky.\" He listens for two seconds as if I'm answering, rolls his eyes and says: \"Fine.\" He shoves the full mug across the table toward the lens so the foam slops over, and says: \"One. Not four.\" He listens again for two seconds, sneers and says: \"Don't push it.\" Then he grabs his own mug, drinks and keeps glaring at me over the rim while the students behind him carry on talking. Dim yellow lamp light. Vertical 9:16. No watermark, no visible phone or camera."),
("she's been on that page for an hour",
"Candid first-person video from my own eye level, as if I just raised my old iPhone across the breakfast table and hit record. "+Q+"the echoing chatter of a huge hall, cutlery on plates and a spoon scraping a bowl. "+N+"The only person who speaks is the blonde girl with the magazine, and she faces the camera when speaking so her lips are visible moving with every word. "+L+
"A vast bright dining hall with tall windows and a blue house banner. Across the table a teenage girl with long wavy pale blonde hair, a blue-bronze tie and radish earrings holds a spoon of porridge halfway to her mouth and stares dreamily into the distance, an upside-down magazine in her other hand. Plates and a goblet are blurred in the foreground. For the first two seconds she keeps the spoon in the air and stares past me, chewing slowly, as if she heard me but is finishing a thought. Then she lowers the magazine, looks at the camera calmly and says with lips moving: \"It's a puzzle. You read it backwards.\" She listens for two seconds as if I'm answering, then adds: \"And upside down. Both.\" She finally eats the spoonful, turns the magazine the right way round, frowns at it, turns it upside down again and says: \"Better. You've got wrackspurts, that's why you can't see it.\" Two seconds pass while she goes back to reading with the spoon raised again, and a student walks past behind her. Grey daylight from the windows. Vertical 9:16. No watermark, no visible phone or camera."),
("he said it wasn't going to snow",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in the snowy village street and hit record. "+Q+"wind, snow crunching, shop bells and three people laughing. "+N+"The only people who speak are the ginger boy with the scarf, the boy with round glasses and the girl with bushy hair, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A snow-covered village street with a shop front, warm lit windows and snow falling. A tall teenage boy with ginger hair, black robes and a red-gold scarf, snow on his shoulders, waves one hand at the sky mid-argument. Behind him a boy with round glasses and a girl with bushy brown hair grin at him. The grey beanie of a friend is blurred large in the bottom corner. For the first two seconds the ginger boy keeps waving his hand at the falling snow and glares up at it, as if he heard me. Then he looks at the camera and says with lips moving: \"That's not proper snow. That's sleet.\" The girl behind him laughs and says to the camera: \"He said clear skies. All week.\" The ginger boy turns back to the camera and says: \"Stop filming me.\" He listens for two seconds as if I'm answering, snow landing on his hair. The boy with glasses leans into frame and says: \"He's still not wearing a hat.\" The ginger boy pulls his robes tight and stomps off toward the shop door, the other two follow him laughing and the camera swings after them. Flat grey daylight, heavy snowfall. Vertical 9:16. No watermark, no visible phone or camera."),
("he named it kevin",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in the greenhouse and hit record. "+Q+"rain tapping on the glass roof, pots clinking and students chatting somewhere behind me. "+N+"The only people who speak are the boy in the grey jumper holding the plant and the girl with long hair in the foreground, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A steamy greenhouse with fogged glass walls and clay pots on a wooden bench. A boy with messy brown hair, a grey jumper and a red-gold tie holds up a muddy uprooted plant with both gloved hands, staring at its dangling roots with a serious face. On the left, very close to the lens and blurred, a girl with long hair stands with her back half to me. For the first two seconds the boy keeps studying the roots, the plant twitches once in his hands and he jerks his head back. Then he looks past the girl straight at the camera and says with lips moving: \"Don't. His name is Kevin.\" He listens for two seconds as if I'm answering, then lifts the plant closer to the lens, roots swinging, and says: \"He's just shy. Look at his little face.\" The girl in the foreground turns her head to the camera, lips moving: \"It's a root. He's talking to a root.\" The plant gives a small muffled squeak, the boy pulls it back against his chest, looks at the camera again and says: \"See? He heard that.\" Two seconds pass with him waiting for my answer, then he goes back to gently brushing soil off the roots and the girl walks out of frame shaking her head. Grey daylight through fogged glass. Vertical 9:16. No watermark, no visible phone or camera."),
]
clips=[dict(n=i,title=t,attach="Startframe = das Bild mit dieser Caption",note="Video 1",img=v) for i,(t,v) in enumerate(V,1)]
WORLDS=[dict(key="hp",name="Wizarding World Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Wizarding Videos Sechserpack</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – WIZARDING WORLD, 6 VIDEO-PROMPTS\nOmni Flash 1.1, 10 Sekunden, 9:16. Für jeden Clip das Bild mit derselben Caption als Startframe nehmen und den VIDEO-Prompt eingeben.\nAlle Dialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Wizarding World, die 6 Video-Prompts zu den 6 Bildern. Startframe ist jeweils das Bild mit derselben Caption.')
open('hp-videos-6.html','w',encoding='utf-8').write(h)
print(len(clips))
