import json, re
Q="2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with "
N="The person holding the camera never speaks and makes no sound. "
L="All dialogue is spoken in English with natural British accents, casual teenage talk. The Snapchat caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. "
V=[
("the owl hates him",
"Startframe: Frühstück in der großen Halle, ein Junge mit runder Brille und schwarzen Haaren hält den Finger hoch, eine weiße Schneeeule auf dem Tisch hat ihn gerade gezwickt, mein Toast unscharf im Vordergrund.",
"Candid first-person video from my own eye level, as if I just raised my old iPhone across the breakfast table and hit record. "+Q+"the echoing chatter of a huge hall, cutlery, feathers rustling and an angry clicking beak. "+N+"The owl never speaks, it only clicks, hoots and flaps. The only person who speaks is the boy with round glasses, and he faces the camera when speaking so his lips are visible moving with every word. "+L+
"A vast candlelit dining hall at breakfast. Across the table a teenage boy with messy black hair, round glasses and a red-gold tie holds up his finger and stares at it, while a big white snowy owl stands on the table between the plates glaring at him. My toast is blurred in the foreground. For the first two seconds he keeps staring at his finger and the owl clicks its beak at him, as if he heard me. Then he looks at the camera and says with lips moving: \"She doesn't hate me. She's just moody.\" He listens for two seconds as if I'm answering, then reaches for the owl again, the owl snaps at his hand and he yanks it back, saying: \"Okay. She hates me a bit.\" He listens again, then pushes his bacon toward the owl with his fork and says: \"Look, bacon. We're friends. See?\" The owl steps on the bacon, looks at him and hoots once, and he shrugs at the camera. Two seconds pass while he sucks his finger and the owl eats. Warm candlelight, grey windows. Vertical 9:16. No watermark, no visible phone or camera."),
("she colour coded the whole week",
"Startframe: Bibliothek, ein Mädchen mit buschigen braunen Haaren sitzt vor einem riesigen Stundenplan mit bunten Feldern, mehrere Bücher aufgeschlagen, mein Ellbogen und mein Buch unscharf im Vordergrund.",
"Candid first-person video from my own eye level, as if I just raised my old iPhone across the library table and hit record. "+Q+"library silence, a quill scratching, pages turning and a whispered argument. "+N+"The only person who speaks is the girl with bushy hair, and she faces the camera when speaking so her lips are visible moving with every word. "+L+
"A dark library with tall bookshelves and green lamps. Across the table a teenage girl with big bushy brown hair and a red-gold tie bends over a huge timetable covered in coloured blocks, a quill in her hand, six open books around her. My elbow and my book are blurred in the foreground. For the first two seconds she keeps colouring in a block with her tongue between her teeth, as if she heard me but doesn't care. Then she looks up at the camera, whispering, lips moving: \"It's not a lot. It's organised.\" She listens for two seconds as if I'm answering, taps the timetable with the quill and whispers: \"Blue is revision, green is more revision.\" She listens again, then holds up a small folded copy of the timetable toward the lens and says: \"I made you one too.\" A librarian hisses shush from somewhere behind me, she drops her voice even lower and mouths sorry, then goes back to colouring. Two seconds pass with her head down again. Green lamp light, dark corners. Vertical 9:16. No watermark, no visible phone or camera."),
("it was earwax",
"Startframe: Gemeinschaftsraum, ein Junge mit roten Haaren sitzt mit verzogenem Gesicht auf dem Sofa, eine offene bunte Bohnenschachtel auf dem Knie, mein Knie und die Sofalehne unscharf im Vordergrund.",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the other end of the sofa and hit record. "+Q+"a crackling fire, a cardboard box rattling and someone gagging. "+N+"The only person who speaks is the ginger boy on the sofa, and he faces the camera when speaking so his lips are visible moving with every word. "+L+
"A warm red common room at night with a fire. On the sofa a tall teenage boy with ginger hair and a red-gold tie sits with his face screwed up, chewing slowly, an open box of multicoloured jelly beans on his knee. My knee and the arm of the sofa are blurred in the foreground. For the first two seconds he keeps chewing with his eyes shut and shudders, as if he heard me. Then he looks at the camera and says with his mouth still half full, lips moving: \"Earwax. Definitely earwax.\" He listens for two seconds as if I'm answering, swallows hard, digs into the box and holds up a green one toward the lens: \"This one's grass. Or bogey.\" He listens again, pops it in, chews twice, freezes and says: \"Bogey.\" He spits it into his hand, throws it into the fire, and holds the box out toward the camera: \"Your turn.\" Two seconds pass with him shaking the box at me and grinning. Warm orange firelight. Vertical 9:16. No watermark, no visible phone or camera."),
("he lost to a first year",
"Startframe: Gemeinschaftsraum, ein blasser Junge mit zurückgegelten weißblonden Haaren starrt auf ein Zauberschachbrett, gegenüber ein winziger Erstklässler mit erhobenen Armen, mein Becher unscharf im Vordergrund.",
"Candid first-person video from my own eye level, as if I just raised my old iPhone next to the chess table and hit record. "+Q+"a quiet common room, small stone chess pieces clicking and a little kid cheering. "+N+"The only people who speak are the pale blond boy and the small first-year boy, and each turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A dim green-lit common room with leather sofas. At a small table a pale teenage boy with slicked-back white-blond hair and a green-silver tie stares down at a wizard chess board where his king lies in pieces, while opposite him a tiny first-year boy in oversized robes has both arms in the air. My goblet is blurred in the foreground. For the first two seconds the blond boy keeps staring at the board and the little boy bounces in his seat, as if they heard me. Then the blond boy looks at the camera with a sour face and says, lips moving: \"He cheated. Obviously.\" The little boy turns to the camera, beaming: \"I didn't cheat.\" The blond boy listens for two seconds as if I'm answering, then snaps: \"Delete that.\" He listens again, then sweeps the pieces off the board with one arm and says: \"Best of three.\" The little boy sets his pieces back up at top speed and says to the camera: \"He said that last time.\" Two seconds pass with the blond boy glaring at me over the board. Cold greenish light. Vertical 9:16. No watermark, no visible phone or camera."),
("she's feeding something",
"Startframe: Waldrand bei grauem Licht, ein Mädchen mit langen hellblonden Haaren und blauer Krawatte hält ein Stück Fleisch in die leere Luft, mein Ärmel und ein Ast unscharf im Vordergrund.",
"Candid first-person video from my own eye level, as if I just raised my old iPhone at the edge of the forest and hit record. "+Q+"wind in the trees, twigs snapping, a soft wet chewing sound from nowhere and birds. "+N+"The only person who speaks is the blonde girl, and she faces the camera when speaking so her lips are visible moving with every word. "+L+
"The edge of a dark forest under grey daylight, wet grass, tall trees. A teenage girl with long wavy pale blonde hair, a blue-bronze tie and a scruffy cardigan stands holding a piece of raw meat out at arm's length into empty air, smiling calmly at nothing. My sleeve and a branch are blurred in the foreground. For the first two seconds she keeps holding the meat out, then it is tugged out of her hand by nothing and vanishes into the air with a chewing sound, and she doesn't flinch. Then she looks at the camera and says, lips moving: \"You can't see him. That's alright.\" She listens for two seconds as if I'm answering, strokes the empty air next to her at head height and says: \"He's very gentle. He likes ears.\" She listens again, then takes a second piece of meat out of her pocket and holds it out toward the lens: \"You can try. Just don't scream, they don't like it.\" The grass in front of her flattens in the shape of a large hoof and the camera jerks back a step. Two seconds pass with her smiling at me and holding out the meat. Flat grey light, mist between the trees. Vertical 9:16. No watermark, no visible phone or camera."),
("he says he's fine",
"Startframe: Vor einer Holzhütte, ein riesiger Mann mit wildem schwarzem Bart und Mantel sitzt auf der Treppe mit einem Verband um die Hand, ein riesiger Hund liegt neben ihm, meine Mütze unscharf im Vordergrund.",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in front of the hut and hit record. "+Q+"wind, a big dog panting, chickens somewhere and a deep rumbling voice. "+N+"The dog never speaks, it only pants and whines. The only person who speaks is the huge bearded man, and he faces the camera when speaking so his lips are visible moving with every word. "+L+
"A wooden hut at the edge of the forest under grey sky, a pumpkin patch. On the front steps a huge man with a wild tangle of black hair and beard and a big moleskin coat sits with one hand wrapped in a bloody bandage, a giant black boarhound lying across his boots. My beanie is blurred in the bottom corner. For the first two seconds he keeps looking at the bandage and pats the dog with the other hand, as if he heard me. Then he looks at the camera and says in a deep gentle voice, lips moving: \"S'nothing. He's only a baby.\" He listens for two seconds as if I'm answering, glances back at the hut where something thumps against the door, and says: \"Don't go in there, mind.\" He listens again, then holds up the bandaged hand and says: \"Still got all me fingers. Mostly.\" The dog lifts its head, whines at the hut door, and the man pushes it back down with a laugh. Two seconds pass with him grinning at me and the door thumping again. Flat grey daylight. Vertical 9:16. No watermark, no visible phone or camera."),
]
clips=[dict(n=i,title=t,attach=a,note="Video 1",img=v) for i,(t,a,v) in enumerate(V,1)]
WORLDS=[dict(key="hp",name="Wizarding World Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Wizarding Videos Sechserpack 2</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – WIZARDING WORLD, 6 NEUE VIDEO-PROMPTS\nOmni Flash 1.1, 10 Sekunden, 9:16. Für jeden Clip das Snap-Bild mit derselben Caption als Startframe nehmen und den VIDEO-Prompt eingeben.\nAlle Dialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Wizarding World, 6 neue Video-Prompts. Unter jeder Caption steht kurz, was auf dem Startframe zu sehen sein muss.')
open('hp-videos-6b.html','w',encoding='utf-8').write(h)
print(len(clips))
