import json, re
S=("Candid first-person video from my own eye level, as if I just raised my old iPhone {how} and hit record. The attached reference snaps define the look of the whole video: match their image quality, softness, muted colours and careless framing. Real live-action phone footage on the real film sets of a gothic wizarding boarding school, real students around 14 years old in black robes, white shirts, grey jumpers and striped house ties, all the recurring people look exactly the same age and the same as in the other clips, NOT anime, NOT cartoon, NOT CGI-looking, no cinematic lighting. "
"2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with {audio}. "
"The person holding the camera never speaks and makes no sound. {speak} All dialogue is spoken in English with natural British accents, casual teenage talk. No caption, no text overlay, no bar on the video. "
"{scene} Vertical 9:16. No watermark, no visible phone or camera.")
H="the 14-year-old girl with big bushy brown hair, a normal mouth and a red-gold tie"; R="the lanky 14-year-old boy with thick straight bright red hair cut in a heavy fringe over his forehead, a long pale face covered in freckles, small blue eyes, a long nose, sticking-out ears, a hand-knitted maroon jumper under his open black robe and a red-gold tie"; HA="the slight 14-year-old boy with untidy black hair, round wire glasses and a thin lightning-shaped scar on his forehead"
SN="the pale teacher in his forties with greasy chin-length black hair, a hooked nose and black robes buttoned to the throat"
V=[
(1,"hermione is in two places","over my breakfast","the echoing chatter of a huge hall, cutlery on tin plates and someone chewing",
 "The only people who speak are "+R+" and "+H+", and each turns their face to the camera before speaking so their lips are visible moving with every word.",
 "A huge stone dining hall at breakfast, grey light from tall windows. Close across the table "+H+" eats cereal with one hand and reads a thick book with the other. Next to her "+R+" chews toast and looks at his plate. My own toast and goblet are blurred in the foreground. For the first two seconds nothing happens, she turns a page and he chews, as if they heard me. Then "+R+" glances at the camera and says with lips moving, mouth half full: \"What. She's reading.\" He listens for two seconds as if I'm answering, and shrugs. "+H+" says without looking up: \"Pass the milk.\" "+R+" slides the jug across to her. Far in the background, small and out of focus, the open doors of the hall: a girl with the same bushy brown hair and the same thick book under her arm walks in, crosses behind the tables and is gone behind a pillar. Nobody at our table notices. "+R+" says to her: \"Are you coming to Herbology or...\" and she says \"Mm.\" without looking up. Two seconds pass with her reading and him buttering another toast. Grey morning light."),
(2,"ron is not okay","in the corridor","an echoing stone corridor, footsteps, students chatting and one boy breathing fast",
 "The only people who speak are "+R+" and "+HA+", and each turns their face to the camera before speaking so their lips are visible moving with every word.",
 "A long stone corridor with tall windows, students walking past blurred. "+R+" stands with his eyes wide open holding "+HA+" by the sleeve, pointing with his other arm at two classroom doors side by side. "+HA+" just looks at him with his hands in his pockets. My bag strap is blurred in the foreground. For the first two seconds "+R+" keeps pointing from one door to the other, as if he heard me. Then he looks at the camera and says with lips moving: \"No, listen. She went in there.\" He listens for two seconds as if I'm answering. "+HA+" looks at the camera and says: \"Okay.\" "+R+" says: \"And then she came out of there.\" "+HA+" says: \"Ron. We've got Charms.\" "+R+" lets go of the sleeve, looks at the two doors once more, and follows him. Two seconds pass with the two of them walking off and "+R+" looking back over his shoulder. Flat grey daylight."),
(3,"she says it's the light","across the library table","library silence, a quill scratching, a page turning and whispering",
 "The only people who speak are "+H+" and "+R+", and each turns their face to the camera before speaking so their lips are visible moving with every word.",
 "A dark library with tall bookshelves and green reading lamps. "+H+" sits behind a tall stack of books writing fast. Opposite her "+R+" sits with his chin on his fists staring at her. My open book is blurred in the foreground. For the first two seconds she keeps writing and he keeps staring, as if they heard me. Then "+R+" looks at the camera and whispers with lips moving: \"Ask her.\" He listens for two seconds as if I'm answering. "+H+" says without looking up: \"Ask me what.\" "+R+" says: \"Nothing.\" "+H+" looks up at the camera, says: \"It's the light in the hall. Ask anyone.\" and goes back to writing. "+R+" looks at the camera and says nothing. Two seconds pass with her quill scratching and him slowly sitting back. Green lamp light, dark corners."),
(4,"arithmancy AND divination","over the table","a quiet common room, parchment rustling and one finger tapping on paper",
 "The only people who speak are "+R+" and "+HA+", and each turns their face to the camera before speaking so their lips are visible moving with every word.",
 "A wooden table in a common room, warm light. Two handwritten timetables on parchment lie side by side, both with the same girl's name at the top. "+R+"'s finger taps on the third lesson of each: one says Arithmancy, the other says Divination, same hour. "+HA+" leans into the frame from the side. My quill and a goblet are blurred at the edge. For the first two seconds the finger keeps tapping between the two entries, as if he heard me. Then "+R+" lowers his face into the frame, looks at the camera and says with lips moving: \"Look. Same time.\" He listens for two seconds as if I'm answering. "+HA+" looks at the camera and says: \"So?\" "+R+" says: \"So she's in both.\" "+HA+" says: \"Maybe she dropped one.\" "+R+" says: \"She doesn't drop things.\" He picks up both timetables and holds them in front of the lens side by side. Two seconds pass with the parchments in his hands and "+HA+" leaning back out of frame. Warm firelight."),
(5,"we followed her","on the stairs","a stone stairwell, footsteps echoing, cloth rustling and whispering",
 "The only people who speak are "+R+" and "+HA+", and each turns their face to the camera before speaking so their lips are visible moving with every word.",
 "A stone spiral staircase seen from below. "+H+" climbs the stairs ahead with her bag over her shoulder, seen from behind, not looking back. Two steps behind her "+R+" and "+HA+" creep upward half hidden under a silvery shimmering cloak, only their legs and part of their faces visible. The banister is blurred in the foreground. For the first two seconds all three keep climbing and the cloak slips a little off "+R+"'s head, as if they heard me. Then "+R+" looks back over his shoulder at the camera and whispers with lips moving: \"Get down.\" He listens for two seconds as if I'm answering. "+HA+" whispers from under the cloak: \"She's not looking.\" "+R+" whispers: \"Shh.\" Above them "+H+" stops on the landing, and both boys freeze on the stairs. She takes something small and gold out from under her collar, looks at it, and turns the corner. "+R+" whispers: \"Go. Go.\" Two seconds pass with the two of them scrambling up after her and the camera following. Cold light from a high window."),
(6,"she was already inside","from the corridor","a stone corridor, a door creaking, a quill scratching inside and one boy out of breath",
 "The only people who speak are "+R+" and "+H+", and each turns their face to the camera before speaking so their lips are visible moving with every word.",
 "A heavy classroom door open a crack, seen from the corridor. Through the gap "+H+" already sits at a desk inside, writing calmly, quill in hand. In the foreground on the corridor "+R+", half cut off by the frame, out of breath, points at the door. My sleeve is blurred at the edge. For the first two seconds "+R+" keeps pointing and "+H+" keeps writing inside, as if they heard me. Then "+R+" turns to the camera and says quietly with lips moving: \"We were right behind her.\" He listens for two seconds as if I'm answering. He pushes the door open a little wider, and "+H+" looks up from her desk toward the door and says: \"You're late.\" "+R+" says: \"We were behind you.\" "+H+" says: \"Sit down, Ron.\" and goes back to writing. Two seconds pass with "+R+" standing in the doorway, not moving, then slowly going in. Grey light through the classroom windows."),
(7,"snape counted 25. there are 24","from my bench","a silent dungeon classroom, bubbling cauldrons, parchment crackling and a slow deep voice",
 "The only person who speaks is "+SN+", and he faces the camera when speaking so his lips are visible moving with every word.",
 "A stone dungeon classroom with candles, shelves of jars and rows of cauldrons. At the front "+SN+" stands holding a parchment register, his eyes moving slowly along the rows of students. In the front row "+H+" looks down into her cauldron and does not move. My own cauldron steams blurred in the foreground. For the first two seconds the teacher's eyes travel along the rows once more and his lips move silently, counting, as if he heard me. Then he looks toward the camera and says slowly, softly, lips moving: \"Twenty-five.\" He listens for two seconds as if I'm answering. He looks down at the register, back up, and says: \"There are twenty-four names on this list.\" He walks one slow step along the front row, stops beside "+H+"'s cauldron, and looks down at her. She keeps stirring. He says: \"Miss Granger. See me after.\" She nods without looking up. Two seconds pass with him standing there and the cauldrons bubbling. Cold greenish candlelight."),
(8,"ron gave up","from the armchair","a crackling fire, a cushion muffling a groan and pages turning",
 "The only people who speak are "+HA+" and "+H+", and each turns their face to the camera before speaking so their lips are visible moving with every word. "+R+" only groans into the cushion.",
 "A warm red common room in the afternoon, fire going. "+R+" lies face down on the sofa with his face buried in a cushion. Next to him "+H+" sits reading a book, a thin gold chain just visible at her collar. In the armchair "+HA+" sits with his feet up. My goblet is blurred in the foreground. For the first two seconds "+R+" doesn't move, "+H+" turns a page and "+HA+" looks at him, as if they heard me. Then "+HA+" looks at the camera and says with lips moving: \"He's been like that since Potions.\" He listens for two seconds as if I'm answering. "+R+" groans something into the cushion. "+H+" says without looking up: \"He'll be fine.\" She tucks the gold chain back under her collar. "+HA+" says: \"Will he?\" "+H+" says: \"Ron. Dinner's in ten minutes.\" Two seconds pass with "+R+" lifting his head an inch, looking at her, and dropping it back into the cushion. Warm firelight."),
(9,"she's asleep. both of her","from my blanket","a dark quiet room, a candle flickering, two people breathing slowly and a page settling",
 "Nobody speaks in this clip, there is no voice at all.",
 "A common room late at night, almost dark, one candle, heavy grain. At the table "+H+" sleeps with her head on her arm over an open book. Further back in the shadows, in an armchair, the same girl with the same bushy hair sleeps again, same robe, a different book open on her lap. Nobody else in the room. My blanket is blurred in the foreground. For the first two seconds nothing moves except the candle flame and the slow breathing of both of them. Then the girl at the table shifts in her sleep and her hand slides off the book. In the same moment the girl in the armchair shifts too, the same movement, and her book slips a little on her lap. The candle flickers. The camera holds completely still. Two seconds pass with both of them breathing in the same rhythm. Dim candlelight, deep shadows."),
]
clips=[dict(n=n,title=t,attach="Kein Startframe. Stil-Referenz-Snaps anhängen, Figuren sind beschrieben",note="Hermine",img=S.format(how=h,audio=a,speak=sp,scene=sc)) for (n,t,h,a,sp,sc) in V]
WORLDS=[dict(key="hp",name="Wizarding Hermione Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Wizarding Hermione Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – WIZARDING WORLD, HERMINE-FOLGE, 9 VIDEO-PROMPTS OHNE STARTFRAME\n10 Sekunden pro Clip, 9:16, Text-zu-Video, in dieser Reihenfolge. Pro Clip die Stil-Referenz-Snaps anhängen. Alle Figuren sind im Prompt beschrieben, keine Namen.\nAlle Dialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund. Kein Caption-Balken im Video, der kommt im Schnitt drüber.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Wizarding World, „hermione is in two places“: 9 Video-Prompts ohne Startframe. Die Caption oben ist der Titel für deinen Schnitt.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('hp-hermione-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
