import json, re
S=("Exact same style as the start image: same image quality, same kind of random bad phone video, just as soft and noisy. Candid first-person video from my own eye level, handheld and a bit shaky, people cut off at the edges. Not a film still, not a studio, not a DSLR. Audio like a phone microphone with {audio}. "
"The person holding the camera never speaks. {speak} All dialogue in English with British accents, short and casual. "
"The Snapchat caption bar with the white text in the picture stays exactly as it is for the whole video, like a fixed overlay. No phone in the picture. "
"{scene} Vertical 9:16.")
V=[
(1,"hermione is in two places","the echo of a big entrance hall, footsteps on stone and students chatting far below",
 "Nobody speaks in this clip, there is no voice at all.",
 "Looking down from a stone gallery into the entrance hall, a wide staircase on the right, grey light from tall windows. The girl with bushy brown hair walks across the flagstones below with her brown bag, seen from above and behind. At the same time the girl with bushy brown hair climbs the staircase on the right, same robe, same bag. Students blurred in the foreground and below. For the first two seconds both keep walking, one across the hall, one up the stairs, at the same pace. Then the one on the stairs stops on a step and adjusts her bag, and the one below stops too, at exactly the same moment, and adjusts hers. A student walks past close in front of the lens, blocking the view for a second. When he's gone, the one on the stairs has reached the top and turns the corner, and the one below walks out through the archway. Two seconds of the empty hall and the camera slowly lowering behind the balustrade."),
(2,"ron is not okay","an echoing stone hall, footsteps and students talking",
 "Only the ginger boy and the boy with glasses speak, each looks at the camera when speaking so their lips are visible moving.",
 "A stone hall with tall windows and two wooden doors side by side. The ginger boy points across at the doors with his arm stretched out, the boy with glasses stands next to him with his hands in his pockets, students walk past blurred in the foreground. For the first two seconds the ginger boy keeps pointing from one door to the other. Then he looks at the camera and says: \"No, listen. She went in there.\" He listens for two seconds as if I'm answering. The boy with glasses looks at the camera and says: \"Okay.\" The ginger boy: \"And then she came out of there.\" The boy with glasses: \"Ron. We've got Charms.\" and walks off. The ginger boy looks at the doors once more and follows him. Two seconds of the two walking away, the ginger boy looking back over his shoulder."),
(3,"she says it's the light","library silence, a quill scratching and whispering",
 "Only the girl with bushy brown hair and the ginger boy speak, each looks at the camera when speaking so their lips are visible moving.",
 "The library, dark shelves, green lamps. The ginger boy sits with his chin on his fists staring sideways, the girl with bushy brown hair next to him writes on a parchment with one hand raised flat toward him without looking up. My open book blurred in the foreground. For the first two seconds she writes and he stares. Then the ginger boy looks at the camera and whispers: \"Ask her.\" He listens for two seconds as if I'm answering. The girl with bushy brown hair says without looking up: \"Ask me what.\" The ginger boy: \"Nothing.\" The girl with bushy brown hair looks up at the camera: \"It's the light in the hall. Ask anyone.\" and goes back to writing. The ginger boy looks at the camera and says nothing. Two seconds of her quill scratching and him sitting back."),
(4,"arithmancy AND divination","a quiet common room, parchment rustling and a finger tapping",
 "Nobody speaks in this clip, there is no voice at all.",
 "A wooden table with two handwritten timetables side by side, both headed the girl with bushy brown hair, a third one lying upside down further back, a pewter goblet and a quill. My own hand in the frame. For the first two seconds my finger rests on the word Arithmancy on the left sheet. Then it slides across to the word Divination on the right sheet, taps it twice, goes back to Arithmancy, and taps again. My hand picks up both sheets, holds them side by side close to the lens so both entries are readable, then lays them back down. Two seconds of the hand resting flat between the two sheets. The camera stays low over the table the whole time."),
(5,"we followed her","a stone stairwell, footsteps and whispering",
 "Only the ginger boy speaks, and he looks at the camera when speaking so his lips are visible moving.",
 "A stone spiral staircase. The girl with bushy brown hair climbs ahead with her brown bag, seen from behind. Two steps behind her the ginger boy creeps upward wrapped in the silvery cloak, looking back over his shoulder at the camera. The banister blurred in the foreground. For the first two seconds both keep climbing and the cloak slips off the ginger boy's shoulder. Then the ginger boy whispers toward the camera: \"Get down.\" He listens for two seconds as if I'm answering. He pulls the cloak back up and whispers: \"Shh.\" Above them the girl with bushy brown hair stops on the landing, the ginger boy freezes on the stairs. She takes a small gold chain out from under her collar, looks at it, and turns the corner. The ginger boy whispers: \"Go. Go.\" Two seconds of him hurrying up after her, the camera following."),
(6,"she was already inside","a stone corridor, a door creaking, a quill scratching inside and one boy out of breath",
 "Only the ginger boy and the girl with bushy brown hair speak, each looks at the camera when speaking so their lips are visible moving.",
 "A heavy wooden classroom door half open, seen from the corridor. Through the gap the girl with bushy brown hair already sits at a desk inside, writing on a parchment scroll, other students at their desks behind her. Close on the right the ginger boy, out of breath, points through the door with his mouth open. For the first two seconds the ginger boy keeps pointing and the girl with bushy brown hair keeps writing. Then the ginger boy turns to the camera and says quietly: \"We were right behind her.\" He listens for two seconds as if I'm answering. He pushes the door open wider, the girl with bushy brown hair looks up from her desk toward the door and says: \"You're late.\" The ginger boy: \"We were behind you.\" The girl with bushy brown hair: \"Sit down, Ron.\" and goes back to writing. Two seconds of the ginger boy standing in the doorway, then slowly going in."),
(7,"snape counted 25. there are 24","a silent dungeon classroom, bubbling cauldrons, parchment and a slow deep voice",
 "Only the teacher in black robes with long black hair speaks, and he faces the camera when speaking so his lips are visible moving.",
 "The potions dungeon, candles, shelves of jars, rows of students at cauldrons seen from behind. At the front the teacher in black robes with long black hair stands with a parchment register in his hands. In front of me the girl with bushy brown hair stirs her cauldron with her head down. My own cauldron steams blurred in the foreground. For the first two seconds the teacher's eyes travel along the rows, lips moving silently, counting. Then he looks up toward the camera and says slowly: \"Twenty-five.\" He listens for two seconds as if I'm answering. He looks down at the register, back up: \"There are twenty-four names on this list.\" He walks slowly down the aisle between the cauldrons, stops beside the girl with bushy brown hair and looks down at her. She keeps stirring. He says: \"Miss Granger. See me after.\" She nods without looking up. Two seconds of him standing there and the cauldrons bubbling."),
(8,"ron gave up","a crackling fire, a groan into a cushion and pages turning",
 "Only the boy with glasses and the girl with bushy brown hair speak, each looks at the camera when speaking so their lips are visible moving. The ginger boy only groans into the cushion.",
 "common room, fire going. Close in the foreground the ginger boy face down on a cushion on the sofa, only his ginger hair visible. Behind him the girl with bushy brown hair reads a book, the boy with glasses sits in the red armchair laughing with a sheet of parchment in his hand. My goblet blurred at the bottom. For the first two seconds the ginger boy doesn't move, the girl with bushy brown hair turns a page, the boy with glasses keeps laughing. Then the boy with glasses looks at the camera and says: \"He's been like that since Potions.\" He listens for two seconds as if I'm answering. The ginger boy groans into the cushion. The girl with bushy brown hair says without looking up: \"He'll be fine.\" She touches a thin gold chain at her collar and tucks it under her jumper. The boy with glasses: \"Will he?\" The girl with bushy brown hair: \"Ron. Dinner's in ten minutes.\" Two seconds of the ginger boy lifting his head an inch, looking back at her, and dropping it into the cushion again."),
(9,"she's asleep. both of her","a dark quiet room, a candle and slow breathing",
 "Nobody speaks in this clip, there is no voice at all.",
 "The common room late at night, one candle. Close in front of me the girl with bushy brown hair sleeps with her head on her arm over an open book. Behind her in the armchair by the fire the same girl with bushy brown hair sleeps again, a book open on her lap. My blanket blurred in the foreground. For the first two seconds nothing moves except the candle flame and their slow breathing. Then the girl at the table shifts in her sleep and her hand slides off the book. In the same moment the girl in the armchair shifts too, the same movement, and her book slips on her lap. The candle flickers. The camera holds still. Two seconds of both of them breathing in the same rhythm."),
]
clips=[dict(n=n,title=t,attach="Startframe = Bild „"+t+"“",note="Hermine",img=S.format(audio=a,speak=sp,scene=sc)) for (n,t,a,sp,sc) in sorted(V)]
WORLDS=[dict(key="hp",name="Wizarding Hermione Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Wizarding Hermione Startframe Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – WIZARDING WORLD, HERMINE-FOLGE, VIDEO-PROMPTS MIT STARTFRAME\n10 Sekunden pro Clip, 9:16. Für jeden Clip das Startframe-Bild mit derselben Caption nehmen und den VIDEO-Prompt eingeben.\nDialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie. Balken bleibt stehen.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Wizarding World, „hermione is in two places“, Version mit Startframes: Video-Prompts auf die fertigen Bilder geschrieben. Die 9 Prompts zu den 9 finalen Bildern.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('hp-hermione-sf-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
