import json, re
S=("Exact same style as the reference images: same image quality, same kind of random bad phone video, just as soft and noisy as the references. Candid first-person video from my own eye level, handheld and a bit shaky, people cut off at the edges, nobody looks at the camera unless they are speaking to me. Not a film still, not a studio, not a DSLR. Audio like a phone microphone with {audio}. "
"The person holding the camera never speaks. {speak} All dialogue in English with British accents, short and casual. "
"A semi-transparent black horizontal Snapchat caption bar spans the full width slightly below the vertical center for the whole video, white Helvetica text, all lowercase, reading exactly: \"{cap}\". No phone in the picture. "
"{scene} Vertical 9:16.")
V=[
(1,"hermione is in two places","the chatter of a big hall, cutlery and chewing",
 "Only Ron Weasley and Hermione Granger speak, each looks at the camera when speaking so their lips are visible moving.",
 "Great Hall at breakfast, grey window light. Close across the table Hermione Granger, bushy brown hair, Gryffindor tie, eats cereal and reads a thick book propped against a jug. Next to her Ron Weasley, ginger, chews toast and looks at his plate. My toast blurred in the foreground. For the first two seconds nothing happens, she turns a page, he chews. Then Ron glances at the camera and says, mouth half full: \"What. She's reading.\" He listens for two seconds as if I'm answering, and shrugs. Hermione says without looking up: \"Pass the milk.\" Ron slides the jug across. Far in the background, small and out of focus, in the open door of the hall, the same girl with the same bushy hair and the same book under her arm walks in and disappears behind a pillar. Nobody at our table notices. Ron says to her: \"Are you coming to Herbology or...\" She says \"Mm.\" Two seconds of her reading and him buttering toast."),
(2,"ron is not okay","an echoing stone corridor, footsteps and students talking",
 "Only Ron Weasley and Harry Potter speak, each looks at the camera when speaking so their lips are visible moving.",
 "A stone corridor with tall windows, students walking past blurred. Ron Weasley, ginger, eyes wide, holds Harry Potter by the sleeve and points at two classroom doors side by side. Harry, glasses, messy black hair, just looks at him with his hands in his pockets. My bag strap blurred in the foreground. For the first two seconds Ron keeps pointing from one door to the other. Then he looks at the camera and says: \"No, listen. She went in there.\" He listens for two seconds as if I'm answering. Harry looks at the camera and says: \"Okay.\" Ron: \"And then she came out of there.\" Harry: \"Ron. We've got Charms.\" Ron lets go of the sleeve, looks at the doors once more and follows him. Two seconds of the two walking off, Ron looking back over his shoulder."),
(3,"she says it's the light","library silence, a quill scratching and whispering",
 "Only Hermione Granger and Ron Weasley speak, each looks at the camera when speaking so their lips are visible moving.",
 "The library, dark shelves, green reading lamps. Hermione Granger sits behind a tall stack of books writing fast. Opposite her Ron Weasley sits with his chin on his fists staring at her. My open book blurred in the foreground. For the first two seconds she writes and he stares. Then Ron looks at the camera and whispers: \"Ask her.\" He listens for two seconds as if I'm answering. Hermione says without looking up: \"Ask me what.\" Ron: \"Nothing.\" Hermione looks up at the camera: \"It's the light in the hall. Ask anyone.\" and goes back to writing. Ron looks at the camera and says nothing. Two seconds of her quill scratching and him sitting back."),
(4,"arithmancy AND divination","a quiet common room, parchment and a finger tapping",
 "Only Ron Weasley and Harry Potter speak, each looks at the camera when speaking so their lips are visible moving.",
 "A wooden table in the Gryffindor common room, warm light. Two handwritten timetables on parchment side by side, both with Hermione's name at the top. Ron Weasley's finger taps on the third lesson of each: one says Arithmancy, the other says Divination, same hour. Harry Potter leans into the frame from the side. My quill and a goblet blurred at the edge. For the first two seconds the finger keeps tapping between the two. Then Ron lowers his face into the frame, looks at the camera and says: \"Look. Same time.\" He listens for two seconds as if I'm answering. Harry looks at the camera: \"So?\" Ron: \"So she's in both.\" Harry: \"Maybe she dropped one.\" Ron: \"She doesn't drop things.\" He picks up both timetables and holds them in front of the lens side by side. Two seconds of the parchments in his hands."),
(5,"we followed her","a stone stairwell, footsteps and whispering",
 "Only Ron Weasley and Harry Potter speak, each looks at the camera when speaking so their lips are visible moving.",
 "A stone spiral staircase from below. Hermione Granger climbs ahead with her bag over her shoulder, seen from behind. Two steps behind her Ron Weasley and Harry Potter creep upward half hidden under the silvery invisibility cloak, only legs and part of their faces visible. The banister blurred in the foreground. For the first two seconds all three keep climbing and the cloak slips off Ron's head. Then Ron looks back over his shoulder at the camera and whispers: \"Get down.\" He listens for two seconds as if I'm answering. Harry whispers from under the cloak: \"She's not looking.\" Ron: \"Shh.\" Above them Hermione stops on the landing, both boys freeze. She takes a small gold chain out from under her collar, looks at it, and turns the corner. Ron whispers: \"Go. Go.\" Two seconds of the two scrambling up after her, the camera following."),
(6,"she was already inside","a stone corridor, a door creaking and a quill scratching",
 "Only Ron Weasley and Hermione Granger speak, each looks at the camera when speaking so their lips are visible moving.",
 "A heavy classroom door open a crack, seen from the corridor. Through the gap Hermione Granger already sits at a desk inside, writing calmly. In the foreground Ron Weasley, half cut off by the frame, out of breath, points at the door. My sleeve blurred at the edge. For the first two seconds Ron keeps pointing and Hermione keeps writing. Then Ron turns to the camera and says quietly: \"We were right behind her.\" He listens for two seconds as if I'm answering. He pushes the door open wider, Hermione looks up toward the door: \"You're late.\" Ron: \"We were behind you.\" Hermione: \"Sit down, Ron.\" and goes back to writing. Two seconds of Ron standing in the doorway, then slowly going in."),
(7,"snape counted 25. there are 24","a silent dungeon classroom, bubbling cauldrons and a slow deep voice",
 "Only Professor Snape speaks, and he faces the camera when speaking so his lips are visible moving.",
 "The potions dungeon, candles, shelves of jars, rows of cauldrons. At the front Professor Snape, greasy black hair, black robes, holds a parchment register and moves his eyes slowly along the rows of students. In the front row Hermione Granger looks down into her cauldron. My own cauldron steaming blurred in the foreground. For the first two seconds Snape's eyes travel along the rows again, lips moving silently, counting. Then he looks toward the camera and says slowly: \"Twenty-five.\" He listens for two seconds as if I'm answering. He looks at the register, back up: \"There are twenty-four names on this list.\" He takes one slow step along the front row, stops beside Hermione's cauldron and looks down at her. She keeps stirring. He says: \"Miss Granger. See me after.\" She nods without looking up. Two seconds of him standing there and the cauldrons bubbling."),
(8,"ron gave up","a crackling fire, a cushion muffling a groan and pages turning",
 "Only Harry Potter and Hermione Granger speak, each looks at the camera when speaking so their lips are visible moving. Ron only groans into the cushion.",
 "Gryffindor common room in the afternoon, fire going. Ron Weasley lies face down on the sofa with his face in a cushion. Next to him Hermione Granger reads a book, a thin gold chain just visible at her collar. In the armchair Harry Potter sits with his feet up. My goblet blurred in the foreground. For the first two seconds Ron doesn't move, Hermione turns a page, Harry looks at him. Then Harry looks at the camera and says: \"He's been like that since Potions.\" He listens for two seconds as if I'm answering. Ron groans into the cushion. Hermione says without looking up: \"He'll be fine.\" She tucks the gold chain back under her collar. Harry: \"Will he?\" Hermione: \"Ron. Dinner's in ten minutes.\" Two seconds of Ron lifting his head an inch, looking at her, and dropping it back."),
(9,"she's asleep. both of her","a dark quiet room, a candle and slow breathing",
 "Nobody speaks in this clip.",
 "The common room late at night, almost dark, one candle, heavy grain. At the table Hermione Granger sleeps with her head on her arm over an open book. Further back in the shadows, in an armchair, the same Hermione Granger sleeps again, same robe, a different book open on her lap. Nobody else in the room. My blanket blurred in the foreground. For the first two seconds nothing moves except the candle flame and their slow breathing. Then the girl at the table shifts in her sleep and her hand slides off the book. In the same moment the girl in the armchair shifts too, the same movement, and her book slips on her lap. The candle flickers. The camera holds still. Two seconds of both of them breathing in the same rhythm."),
]
clips=[dict(n=n,title=t,attach="Kein Startframe. Stil-Referenz-Snaps anhängen",note="Hermine",img=S.format(audio=a,speak=sp,cap=t,scene=sc)) for (n,t,a,sp,sc) in V]
WORLDS=[dict(key="hp",name="Wizarding Hermione Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Wizarding Hermione Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – WIZARDING WORLD, HERMINE-FOLGE, 9 VIDEO-PROMPTS OHNE STARTFRAME\n10 Sekunden pro Clip, 9:16, Text-zu-Video, in dieser Reihenfolge. Pro Clip die Stil-Referenz-Snaps anhängen. Figuren mit Namen, Caption-Balken im Video.\nDialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Wizarding World, „hermione is in two places“: 9 Video-Prompts ohne Startframe, nach deinem Muster: Namen, kurz, Balken im Video.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('hp-hermione-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
