import json, re
Q="2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with "
N="The person holding the camera never speaks and makes no sound. "
L="All dialogue is spoken in English with natural British accents, casual teenage talk. The Snapchat caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. "
NIF="The niffler never speaks, it only chitters, squeaks and scurries. "
V=[
(1,"it took the trap","Startframe = Bild „it took the trap“",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in the corridor and hit record. "+Q+"an echoing stone cloister, torches crackling, a small creature chittering and two identical voices. "+N+NIF+"The only people who speak are the two ginger twins, and each turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A long stone cloister at night lit by torches. On the left two identical teenage boys with ginger hair, black robes and red-gold ties stand looking down the corridor, one holding a long butterfly net. Further down the corridor a small black niffler with a long snout sits on the flagstones holding a shiny gold coin in its paws. On the floor near the camera lies an open, empty sweet wrapper. For the first two seconds the twins keep staring at the niffler and the niffler keeps turning the coin over, as if they heard me. Then the twin with the net looks at the camera and says with lips moving: \"That was the bait. It took the bait and left the trap.\" He listens for two seconds as if I'm answering. The other twin looks at the camera and says: \"Honestly, I respect it.\" The twin with the net takes one slow step forward, the niffler looks up, and both freeze. He whispers to the camera: \"Nobody move.\" The niffler stuffs the coin into its belly pouch, scurries straight between the twins' legs, and both spin round swinging the net at nothing. Two seconds pass with the twins staring after it down the corridor and the empty wrapper lying at my feet. Warm torchlight, dark arches. Vertical 9:16. No watermark, no visible phone or camera."),
(2,"it took draco's ring. he's fine","Startframe = Bild „it took draco's ring. he's fine“",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in the cloister and hit record. "+Q+"a busy stone cloister, footsteps, robes rustling and one furious voice. "+N+"The only person who speaks is the pale boy with white-blond hair, and he faces the camera when speaking so his lips are visible moving with every word. "+L+
"A stone cloister in grey daylight, students in black robes walking past. In the middle a pale teenage boy with slicked white-blond hair and a green-silver tie holds up his bare right hand in front of his face and stares at it, furious. Behind him two big boys in green-silver ties crouch on the flagstones searching the floor. For the first two seconds the blond boy keeps staring at his empty finger and the two boys behind him keep patting the floor, as if he heard me. Then he looks at the camera and says with lips moving: \"That was my grandfather's ring. My grandfather's.\" He listens for two seconds as if I'm answering, then snaps: \"I'm fine. I'm completely fine.\" He spins round to the crouching boys and shouts: \"Why are you looking there, it ran that way!\" and points down the cloister, and both boys scramble up and run the wrong way. He turns back to the camera and says: \"Delete that.\" Two seconds pass with him standing alone in the cloister, hand still raised, students walking round him. Flat grey light. Vertical 9:16. No watermark, no visible phone or camera."),
(3,"hagrid brought a bucket","Startframe = Bild „hagrid brought a bucket“",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in the entrance hall and hit record. "+Q+"a huge echoing hall, heavy boots, a metal bucket clanking and a deep warm voice. "+N+"The only person who speaks is the giant bearded man, and he faces the camera when speaking so his lips are visible moving with every word. "+L+
"A huge stone entrance hall with big wooden doors open behind. A giant of a man with a wild tangle of black hair and beard and a long brown moleskin coat walks toward the camera carrying a tin bucket in one hand and a cloth sack in the other. Behind him walk a boy with round glasses and black hair, a ginger boy and a girl with bushy brown hair. The back of another student's head is blurred on the left. For the first two seconds the giant man keeps walking toward me with the bucket swinging, as if he heard me. Then he looks at the camera and says in a deep gentle voice, lips moving: \"Right. Where is it. Nobody panic.\" He listens for two seconds as if I'm answering, then holds up the bucket and says: \"Yeh put the shiny stuff in the bucket. It climbs in. Simple.\" The ginger boy behind him says something and the giant man looks back over his shoulder and rumbles: \"No, it won't bite. Much.\" Then he looks at the camera again, winks, and says: \"Got a bit o' gold in the sack. It'll come.\" Two seconds pass with him walking past the camera and the three behind him hurrying to keep up. Grey daylight through the doors. Vertical 9:16. No watermark, no visible phone or camera."),
(4,"everyone got their stuff back. except draco","Startframe = Bild „everyone got their stuff back. except draco“",
"Candid first-person video from my own eye level, as if I just raised my old iPhone across the table and hit record. "+Q+"the echoing chatter of a huge hall, benches scraping and laughter. "+N+"The only people who speak are the ginger boy and the pale blond boy, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A huge candlelit dining hall, a long wooden bench in the foreground, students everywhere. A round-faced boy with dark hair holds up a pair of round glasses and checks them. A ginger boy with a red-gold tie looks at a watch on his wrist and grins. A girl with long red hair looks down at a small coin in her hands. On the left a pale boy with white-blond hair and a green-silver tie stands with his arms crossed and a sour face, holding nothing. For the first two seconds the ginger boy keeps admiring his watch and the blond boy keeps glaring at it, as if they heard me. Then the ginger boy looks at the camera and says with lips moving: \"It was in the bucket. Everything was in the bucket.\" He listens for two seconds as if I'm answering. The blond boy looks at the camera and says: \"Not everything.\" The ginger boy holds up his wrist toward the blond boy and says: \"Maybe it just liked your ring more, Malfoy.\" The blond boy says: \"It's a family heirloom.\" The round-faced boy puts his glasses on and looks at the blond boy through them, and the ginger boy laughs. Two seconds pass with the blond boy glaring at me over his crossed arms. Warm candlelight. Vertical 9:16. No watermark, no visible phone or camera."),
(5,"hagrid said we can't keep it","Startframe = Bild „hagrid said we can't keep it“",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the top of the steps and hit record. "+Q+"wind, boots crunching in snow, a bucket clanking and a small creature chittering. "+N+NIF+"The only person who speaks is the giant bearded man, and he turns his head back toward the camera when speaking so his lips are visible moving with every word. "+L+
"A snowy stone courtyard at dusk, a wooden hut with a lit window in the distance, mountains behind. A giant man with a wild tangle of black hair and a long brown coat walks away from the camera through the snow carrying a tin bucket, and a small black niffler sits in his coat pocket looking back at me, holding a silver ring in its paws. A stone balustrade is blurred in the foreground. For the first two seconds the giant man keeps walking away and the niffler in his pocket keeps turning the ring in its paws, as if they heard me. Then the giant man stops, turns his head back over his shoulder toward the camera and says in a deep gentle voice, lips moving: \"No. Yeh can't keep it. It's goin' back to the forest.\" He listens for two seconds as if I'm answering, then says: \"I know. I know. It's got a face on it.\" He looks down at the niffler in his pocket, the niffler holds up the ring to him and chitters, and he mutters: \"Yeah, an' we're givin' that back too. Eventually.\" He turns and keeps walking toward the hut, and the niffler waves the ring at the camera until they're small in the snow. Two seconds pass with only the wind and the bucket clanking. Cold blue dusk light. Vertical 9:16. No watermark, no visible phone or camera."),
]
clips=[dict(n=n,title=t,attach=a,note="Niffler",img=v) for (n,t,a,v) in sorted(V)]
WORLDS=[dict(key="hp",name="Wizarding Niffler Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Wizarding Niffler Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – WIZARDING WORLD, NIFFLER-VIDEO, VIDEO-PROMPTS\nOmni Flash 1.1, 10 Sekunden, 9:16. Für jeden Clip das Startframe-Bild mit derselben Caption nehmen und den VIDEO-Prompt eingeben. Keine Charakter-Referenzen nötig, die Figuren sind beschrieben.\nAlle Dialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie. Der Niffler macht nur Laute. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Wizarding World, Niffler-Video: Video-Prompts zu den fertigen Startframes, in Story-Reihenfolge nummeriert. Weitere Clips kommen dazu, sobald Bilder da sind.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('hp-niffler-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
