import json, re
from describe import describe, MAR
Q="2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with "
N="The person holding the camera never speaks and makes no sound. "
L="All dialogue is spoken in English with natural British accents, casual teenage talk. The Snapchat caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. "
PETER="Peter, the short chubby blond boy,"
V=[
(2,"padfoot is taking bets","@PADFOOT, @MOONY (Peter wird beschrieben)",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the sofa and hit record. "+Q+"a crackling fire, coins clinking and a quill scratching on parchment. "+N+"The only people who speak are @PADFOOT and Peter, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A stone common room with tapestries and a fire. @PADFOOT sits in a red armchair with a parchment list of names and bets on his knee and a pile of gold and silver coins beside it, holding out his hand. "+PETER+" kneels in front of him handing over a coin with a worried face. In the background @MOONY sits on a sofa reading a book with one hand raised, refusing to take part. My knee in grey trousers is blurred in the foreground. For the first two seconds @PADFOOT keeps his hand out and Peter keeps hesitating with the coin, as if they heard me. Then @PADFOOT looks at the camera and says with lips moving: \"Two galleons says she says no before he finishes the sentence.\" He listens for two seconds as if I'm answering. Peter looks at the camera and says quietly: \"I'm putting three on maybe.\" @PADFOOT takes the coin, writes on the list without looking up and says: \"Maybe isn't an answer, Wormtail.\" Peter says: \"It is with her.\" @PADFOOT looks at the camera, shrugs, and adds the coin to the pile. @MOONY turns a page without looking up. Two seconds pass with @PADFOOT counting the coins. Warm firelight, grey daylight from the window. Vertical 9:16. No watermark, no visible phone or camera."),
(6,"he fell off","@PADFOOT, @MOONY, @PRONGS (Peter wird beschrieben)",
"Candid first-person video from my own eye level, as if I just raised my old iPhone while standing over him and hit record. "+Q+"wind over a grass pitch, someone laughing hard, chewing and a groan. "+N+"The only people who speak are @PADFOOT, @MOONY and @PRONGS, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A wide green pitch under a grey sky. @PRONGS lies flat on his back on the grass in a muddy black robe with his glasses crooked, a broomstick beside him, eyes closed. @PADFOOT stands over him with his hand over his mouth trying not to laugh, @MOONY crouches at his side looking worried, and "+PETER+" stands at the right edge eating a pasty. The toe of my own trainer is blurred large at the bottom. For the first two seconds @PRONGS doesn't move, @PADFOOT's shoulders shake with silent laughter and Peter keeps chewing, as if they heard me. Then @MOONY looks up at the camera and says with lips moving: \"He's fine. He's breathing. He's just embarrassed.\" He listens for two seconds as if I'm answering. @PADFOOT takes his hand off his mouth and says: \"She was watching. From the stands. The whole time.\" @PRONGS opens his eyes, looks at the camera without lifting his head and says: \"Did she see the loop?\" @PADFOOT says: \"She saw the ground.\" @PRONGS closes his eyes again. Peter takes another bite. Two seconds pass with @MOONY patting @PRONGS's shoulder. Flat grey daylight. Vertical 9:16. No watermark, no visible phone or camera."),
(4,"she gave it back with corrections","@PRONGS, @PADFOOT",
"Candid first-person video from my own eye level, as if I just raised my old iPhone across the table and hit record. "+Q+"a busy common room, a fire, parchment crackling and one boy laughing so hard he wheezes. "+N+"The only people who speak are @PRONGS and @PADFOOT, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A stone common room at night, fire and candles behind. In the foreground a sheet of parchment is held up close to the lens: a handwritten love poem covered in red ink corrections, crossed-out words, arrows, the word spelling circled and a big red 6 out of 10 at the bottom. Behind it @PRONGS stares at the sheet with his mouth wide open, and @PADFOOT leans over his shoulder laughing. For the first two seconds @PRONGS keeps staring at the red ink and @PADFOOT keeps laughing, as if they heard me. Then @PRONGS looks at the camera and says with lips moving: \"Six. Out of ten. She marked it.\" He listens for two seconds as if I'm answering. @PADFOOT points at the sheet and reads out, wheezing: \"No music. She wrote no music next to it.\" @PRONGS grabs the parchment, looks at the camera and says: \"Six is a pass. Six is technically a pass.\" @PADFOOT says: \"She corrected your spelling of her name, James.\" @PRONGS looks at the sheet again and goes quiet. Two seconds pass with @PADFOOT wiping his eyes and @PRONGS folding the sheet very carefully and putting it in his pocket. Warm candlelight. Vertical 9:16. No watermark, no visible phone or camera."),
(8,"she said maybe. he hasn't spoken since","@PRONGS, @PADFOOT, @EVANS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone over my mug and hit record. "+Q+"a crackling fire, a hand waving through the air, pages turning and a quiet common room. "+N+"The only people who speak are @PADFOOT and @EVANS, and each turns their face to the camera before speaking so their lips are visible moving with every word. @PRONGS never speaks in this clip. "+L+
"A stone common room by the fire. @PRONGS sits in a leather armchair with his arm in a white sling, staring into the distance with a small dazed smile, not blinking. @PADFOOT stands next to him waving a hand up and down in front of his face. In the background @EVANS sits at a desk holding a book up in front of her face, only her eyes and red hair visible over the top, watching. My mug is blurred large in the foreground. For the first two seconds @PADFOOT keeps waving his hand in front of @PRONGS's eyes and @PRONGS keeps smiling at nothing, as if they heard me. Then @PADFOOT looks at the camera and says with lips moving: \"Three hours. She said maybe and he just stopped.\" He listens for two seconds as if I'm answering. He snaps his fingers next to @PRONGS's ear, nothing happens, and he says: \"I've tried food. I've tried insulting him.\" @EVANS lowers the book a little, looks at the camera and says quietly: \"I only said maybe.\" @PRONGS's smile gets a tiny bit wider. @PADFOOT looks at the camera and says: \"See? That. That's all he does now.\" Two seconds pass with @EVANS raising the book back over her face and @PRONGS smiling at the fire. Warm firelight. Vertical 9:16. No watermark, no visible phone or camera."),
(9,"padfoot lost 3 galleons","@PADFOOT, @MOONY (Peter wird beschrieben)",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in the cloister and hit record. "+Q+"an echoing stone cloister, gold coins clinking and a boy giggling. "+N+"The only people who speak are @PADFOOT and Peter, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A stone cloister with arched windows in grey daylight. @PADFOOT stands with a sour face dropping gold coins one by one into the open hand of "+PETER+" who grins from ear to ear. Behind them @MOONY walks past looking at the floor. My own sleeve in a red-gold striped jumper is blurred in the foreground. For the first two seconds @PADFOOT keeps dropping the coins slowly, one at a time, and Peter's grin gets wider, as if they heard me. Then @PADFOOT looks at the camera and says with lips moving: \"Maybe. She said maybe. Who bets on maybe.\" He listens for two seconds as if I'm answering. Peter closes his hand around the coins, looks at the camera and says: \"I did. Three galleons.\" @PADFOOT says: \"It's not even an answer.\" Peter says: \"It is with her.\" @MOONY, walking past, says nothing but holds up one finger without looking, and @PADFOOT groans and drops the last coin. Two seconds pass with Peter counting the coins and @PADFOOT glaring at me. Soft grey light. Vertical 9:16. No watermark, no visible phone or camera."),
(1,"attempt 47. it's 8am","@PRONGS, @PADFOOT, @EVANS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone over my breakfast and hit record. "+Q+"the echoing chatter of a huge hall, cutlery on tin plates and one boy far too cheerful for the morning. "+N+"The only people who speak are @PRONGS, @PADFOOT and @EVANS, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A huge stone dining hall at breakfast, tall grey windows. @PRONGS leans across the table with a big grin holding out a single daisy. Next to him @PADFOOT sits grinning down at his toast. On the right @EVANS holds a book up in front of her face and has one hand raised flat toward the daisy without looking. Another girl and my own plate are blurred in the foreground. For the first two seconds @PRONGS keeps holding the daisy out and @EVANS keeps her hand up and her book up, as if they heard me. Then @PRONGS looks at the camera and says with lips moving: \"Forty-seven. Lucky number. I can feel it.\" He listens for two seconds as if I'm answering. @EVANS lowers the book just enough to look at the camera and says: \"It's eight in the morning.\" @PRONGS turns back to her and says: \"That's why I brought a flower. Breakfast flower.\" @PADFOOT looks at the camera and says: \"Forty-six was a poem. This is progress.\" @EVANS takes the daisy without a word, puts it in her goblet and raises the book again. @PRONGS stares at the goblet, then at the camera, and mouths yes. Two seconds pass with @PADFOOT patting him on the back. Grey morning light. Vertical 9:16. No watermark, no visible phone or camera."),
(3,"he wrote a poem","@PRONGS, @EVANS, @MOONY",
"Candid first-person video from my own eye level, as if I just raised my old iPhone while walking beside them and hit record. "+Q+"an echoing stone cloister, footsteps, a boy reciting far too loudly and someone groaning. "+N+"The only people who speak are @PRONGS, @EVANS and @MOONY, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A stone cloister in grey daylight, students walking past blurred. @PRONGS walks along reading from a sheet of parchment with one hand pressed to his chest, reciting. Beside him @EVANS walks with her books hugged to her chest and her eyes closed in patience. Behind them @MOONY walks with his hand over his face. For the first two seconds @PRONGS keeps reciting silently from the sheet and @EVANS keeps her eyes closed, as if they heard me. Then @PRONGS looks at the camera, clears his throat and reads out with lips moving: \"Let messing blord the bird matter, the corrected they jow tomor.\" He listens for two seconds as if I'm answering. @EVANS opens her eyes, looks at the camera and says: \"It doesn't rhyme. It doesn't have words.\" @MOONY takes his hand off his face, looks at the camera and says: \"I told him to sleep on it. He slept on it. This is after.\" @PRONGS holds the sheet out to @EVANS and says: \"Keep it. Read it later. It's better later.\" @EVANS takes the sheet, tucks it into her book and keeps walking. Two seconds pass with @PRONGS looking at the camera with huge hopeful eyes and @MOONY shaking his head. Flat grey light. Vertical 9:16. No watermark, no visible phone or camera."),
(5,"plan b: quidditch","@PADFOOT, @EVANS, @PRONGS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone over the railing of the stands and hit record. "+Q+"a roaring crowd, wind, a broomstick whooshing past and one boy groaning through his hands. "+N+"The only people who speak are @PADFOOT and @EVANS, and each turns their face to the camera before speaking so their lips are visible moving with every word. @PRONGS is too far away to speak. "+L+
"A wooden stand full of students in scarves, a green pitch below with tall goal towers. Out over the pitch @PRONGS in red-gold quidditch robes hangs upside down mid-loop on his broomstick with a swirl of motion behind him. In the row in front of me @EVANS sits with her head down reading a book, not watching, and next to her @PADFOOT has both hands over his face. A wooden railing with a red-gold scarf is blurred in the foreground. For the first two seconds @PRONGS completes the loop and wobbles, the crowd gasps, @EVANS turns a page without looking up, as if they heard me. Then @PADFOOT lowers his hands, looks back at the camera and says with lips moving: \"He's doing the loop. He's doing the loop for her.\" He listens for two seconds as if I'm answering. @EVANS looks up at the camera, not at the pitch, and says: \"Is he still up there?\" @PADFOOT says: \"He's doing a second one.\" @EVANS says: \"Tell me when he's done.\" and goes back to her book. Out on the pitch @PRONGS pulls into another loop, waves with one hand toward the stands, and the broom lurches. @PADFOOT puts his hands back over his face. Two seconds pass with the crowd going ooh and @EVANS turning a page. Grey daylight. Vertical 9:16. No watermark, no visible phone or camera."),
(7,"hospital wing. she visited.","@EVANS, @PRONGS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the next bed and hit record. "+Q+"a quiet echoing ward, sheets rustling and two people trying not to sound pleased. "+N+"The only people who speak are @EVANS and @PRONGS, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A bright hospital ward with white iron beds and tall arched windows, warm late sun. @PRONGS sits up in bed in striped pyjamas with his arm in a sling, grinning at @EVANS. @EVANS stands at the foot of the bed with her arms crossed, trying to look stern and failing, a small smile on her face. A bar of chocolate lies on the bedside table. The white blanket of my own bed is blurred in the foreground. For the first two seconds they just look at each other, @EVANS with her eyebrows up and @PRONGS grinning, as if they heard me. Then @EVANS looks at the camera and says with lips moving: \"I'm only here because Remus asked me to bring the chocolate.\" She listens for two seconds as if I'm answering. @PRONGS looks at the camera and says: \"She's been here twenty minutes.\" @EVANS says to the camera: \"The chocolate was heavy.\" @PRONGS says: \"Did you see the loop?\" @EVANS looks at him, looks at the camera, and says: \"I saw the ground.\" She uncrosses her arms, sits down on the edge of the bed, and @PRONGS looks at the camera with his mouth open. Two seconds pass with neither of them saying anything. Warm golden light. Vertical 9:16. No watermark, no visible phone or camera."),
]
clips=[dict(n=n,title=t,attach="Startframe = Bild "+str(n)+" („"+t+"“), keine Referenzen, Personen beschrieben",note="Lily",img=describe(v,MAR)) for (n,t,a,v) in sorted(V)]
WORLDS=[dict(key="mar",name="Marauders Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Marauders Lily Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – MARAUDERS, LILY-FOLGE, VIDEO-PROMPTS\nOmni Flash 1.1, 10 Sekunden, 9:16. Für jeden Clip das Startframe-Bild mit derselben Caption nehmen, die genannten Referenzen anhängen und den VIDEO-Prompt eingeben.\nAlle Dialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund. Keine @-Referenzen: alle Personen sind so beschrieben, wie sie auf dem Startframe aussehen.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Marauders, die Lily-Folge: Video-Prompts zu den fertigen Startframes. Alle 9 Clips in Story-Reihenfolge.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('marauders-lily-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
