import json, re
Q="2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with "
N="The person holding the camera never speaks and makes no sound. "
L="All dialogue is spoken in English with natural British accents, casual teenage talk. The Snapchat caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. "
PETER="Peter, the short chubby blond boy,"
V=[
(1,"they've been at this for a week","@PRONGS, @PADFOOT, @MOONY",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from my bed and hit record. "+Q+"a crackling candle, a quill scratching, parchment rustling and a boy sighing. "+N+"The only people who speak are @PRONGS and @PADFOOT, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A dormitory at night, the whole floor covered in sheets of parchment joined into one big hand-drawn map of a castle. In the middle of it @PRONGS lies on his stomach in a white shirt and loosened red-gold tie, drawing with a quill, glasses pushed up into his messy hair, ink on his fingers. Behind him @PADFOOT lies on a bed with his feet up, holding a sheet above his face. On the right @MOONY sits on a chair reading a sheet, half cut off by the edge. My sock is blurred in the bottom corner. For the first two seconds nobody looks up, @PRONGS keeps drawing and @PADFOOT keeps squinting at his sheet, as if they heard me. Then @PRONGS looks up at the camera and says with lips moving: \"It's nearly done. Two more floors.\" He listens for two seconds as if I'm answering. @PADFOOT lowers his sheet, looks at the camera and says: \"He said that on Monday.\" @PRONGS throws a balled-up sheet at the bed without looking and says: \"Monday I meant it less.\" @MOONY shakes his head and goes back to reading. Two seconds pass with @PADFOOT laughing and @PRONGS drawing again. Warm candlelight. Vertical 9:16. No watermark, no visible phone or camera."),
(2,"the stag looks like a goat","@PRONGS, @PADFOOT",
"Candid first-person video from my own eye level, as if I just raised my old iPhone with my other hand and hit record. "+Q+"a crackling candle, someone laughing hard and parchment crumpling. "+N+"The only people who speak are @PRONGS and @PADFOOT, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A dim common room at night, candles, parchment sheets all over the rug. Close to the lens my own ink-stained hand holds up a scrap of parchment with a small ink drawing of a stag whose antlers look exactly like goat horns. Behind it, out of focus, @PRONGS sits on the floor in his black robe looking at the drawing with his mouth pressed shut, and @PADFOOT sits next to him laughing with his head thrown back. For the first two seconds my hand turns the drawing slowly in the candlelight and @PADFOOT keeps laughing, as if they heard me. Then @PRONGS looks at the camera and says, lips moving: \"It's a stag. That's clearly a stag.\" He listens for two seconds as if I'm answering. @PADFOOT wipes his eyes, looks at the camera and says: \"It's got a beard, James. Stags don't have beards.\" @PRONGS reaches forward and grabs the drawing out of my hand, so it disappears from the frame, and says: \"The antlers are the hard part.\" @PADFOOT falls sideways onto the rug laughing again. Two seconds pass with @PRONGS scratching at the drawing with his thumb and @PADFOOT lying on the floor. Warm candlelight, dark corners. Vertical 9:16. No watermark, no visible phone or camera."),
(3,"remus is the only one actually working","@MOONY, @PADFOOT",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from my bed and hit record. "+Q+"one quill scratching steadily, a candle flickering, a soft snore from the bed behind. "+N+"The only person who speaks is @MOONY, and he turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A dormitory very late at night, one candle on the windowsill, stone walls, four-poster beds. In the foreground @MOONY sits hunched over a small desk covered in books, writing tiny words onto a long strip of parchment with a quill, a half-eaten bar of chocolate in foil beside his hand. On the bed behind him @PADFOOT lies asleep on his side with his dark hair over his face, one arm hanging off the mattress. For the first two seconds @MOONY keeps writing without looking up, only his eyebrows go up, as if he heard me. Then he glances at the camera and says quietly, lips moving: \"Someone has to spell the corridors right.\" He listens for two seconds as if I'm answering, breaks off a piece of chocolate, eats it, and says: \"He did the whole dungeon level. Then he lay down on it.\" He looks over his shoulder at @PADFOOT, back at the camera, and says: \"I'm not waking him. He drools on the ink.\" @PADFOOT snores louder and rolls onto his back. Two seconds pass with @MOONY writing again and the candle flickering. Dim orange light, dark corners. Vertical 9:16. No watermark, no visible phone or camera."),
(6,"filch nearly got us","@MOONY (Padfoot ist auf dem Bild der schwarze Hund)",
"Candid first-person video from my own eye level, as if I just raised my old iPhone behind the tapestry and hit record. "+Q+"three people breathing as quietly as they can, a dog panting softly, a cat meowing and slow footsteps with a creaking lantern on the other side of the cloth. "+N+"The black dog never speaks, it only pants and whines. The only people who speak are @MOONY and Peter, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A cramped dark gap between a stone wall and the back of a thick tapestry, orange lantern light glowing through the fabric and the sharp shadow of a cat standing on it. Squeezed together on the floor are @MOONY with his eyes shut and his hand pressed over his own mouth, "+PETER+" with huge frightened eyes, and a big black dog wedged between them. My own shoulder is blurred in the foreground. For the first two seconds nobody moves, the lantern light sways across their faces and the cat's shadow turns its head, as if they heard me and are begging me to be quiet. Then @MOONY opens his eyes, looks at the camera and mouths almost without sound, lips moving: \"Don't. Breathe.\" He listens for two seconds while the footsteps come closer and stop right behind the cloth. Peter whispers to the camera in a tiny voice: \"I need to sneeze.\" The black dog turns its head and stares at Peter, and @MOONY whispers: \"If you sneeze, the dog eats you.\" The footsteps move away, the lantern light fades from the tapestry, and all three sag against the wall. The dog lets out a long breath and Peter wipes his nose on his sleeve. Two seconds pass with @MOONY silently laughing into his hand. Almost black, one orange glow. Vertical 9:16. No watermark, no visible phone or camera."),
(7,"lily wants to know what we're doing","@EVANS, @PRONGS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone over my mug and hit record. "+Q+"a busy common room, a fire, chatter and one very calm girl's voice. "+N+"The only people who speak are @EVANS and @PRONGS, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A stone common room in the afternoon, red armchairs, students blurred in the background. @EVANS stands with her arms crossed and one eyebrow raised, looking straight at @PRONGS. @PRONGS stands in front of her in a grey jumper, one hand scratching the back of his head, a big roll of parchment held behind his back, smiling far too innocently. My orange mug is blurred large in the bottom of the frame. For the first two seconds @EVANS keeps staring at @PRONGS and @PRONGS keeps smiling and scratching his head, and neither of them blinks, as if they heard me. Then @EVANS turns her head to the camera and says, lips moving: \"He's hiding something. Look at his face.\" She listens for two seconds as if I'm answering. @PRONGS looks at the camera and says: \"It's homework. A very large homework.\" @EVANS says to the camera: \"He hasn't done homework since second year.\" @PRONGS takes one step back, the roll slips out of his hand and unrolls across the floor behind him, and he says: \"Alright, it's a map. Don't tell her.\" @EVANS says: \"I'm standing right here.\" Two seconds pass with @PRONGS scrambling to roll the map back up and @EVANS shaking her head at me. Warm light from the fire. Vertical 9:16. No watermark, no visible phone or camera."),
(8,"the password","@PADFOOT, @PRONGS, @MOONY",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from my bed with my feet up and hit record. "+Q+"candles flickering, bedsprings creaking, groaning, laughing and a wand tapping on parchment. "+N+"The only people who speak are @PADFOOT, @PRONGS and @MOONY, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A dormitory at night lit by candles, trunks and clutter in the background. @PADFOOT stands on a bed in a white shirt with his wand raised like he's giving a speech, mouth open mid-word. On the floor in front of the bed @PRONGS sits with his head in both hands. On the bed behind @PADFOOT, @MOONY lies flat with a pillow pressed over his face. A folded blank parchment lies on the red blanket by @PADFOOT's feet. My own foot in a grey sock is blurred large in the foreground. For the first two seconds @PADFOOT keeps his wand raised and looks around for applause, as if he heard me. Then he looks at the camera and says, lips moving: \"I solemnly swear that I am up to no good. That's the password. Genius.\" He listens for two seconds as if I'm answering. @MOONY lifts the pillow off his face, looks at the camera and says: \"It's nine words. Nine.\" @PRONGS looks up from his hands and says: \"It's the worst thing I've ever heard.\" @PADFOOT crouches down, points his wand at the folded parchment on the blanket, says the phrase again quietly, and thin ink lines spread across the blank surface. @PRONGS and @MOONY both sit up and stare at it. @PRONGS says: \"...it's perfect.\" Two seconds pass with @PADFOOT standing back up on the bed and bowing. Warm candlelight, dark corners. Vertical 9:16. No watermark, no visible phone or camera."),
(9,"it works","@PRONGS, @PADFOOT, @MOONY (Peter wird beschrieben)",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the rug and hit record. "+Q+"a candle flickering, parchment rustling, ink scratching by itself and four boys going quiet and then whooping. "+N+"The only people who speak are @PRONGS and @PADFOOT, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A common room at night, four boys sitting cross-legged on a patterned rug around a big parchment map with a candle standing in the middle of it, thin ink corridors and tiny labelled dots drawn on it. From left to right: @PRONGS with his glasses, pointing at the map with his mouth open, @PADFOOT leaning forward with his elbows on his knees, @MOONY with his chin on his fist, and "+PETER+" chewing his thumbnail. My bare knee is blurred large in the bottom of the frame. For the first two seconds nobody says anything, they just watch the tiny dots creep along the ink corridors, as if they heard me and can't answer. Then @PRONGS looks up at the camera with a huge grin, lips moving: \"Every single person. Every floor. Look, that's Filch.\" He listens for two seconds as if I'm answering. @PADFOOT taps a dot in the corner of the map, looks at the camera and says: \"And that's Peter's dot. In the bathroom. Ten minutes ago.\" Peter mumbles that he had to go and @MOONY snorts. @PRONGS pulls out his wand, taps the map and says to the camera: \"Mischief managed.\" The ink lines drain away until the parchment is blank around the candle, and all four boys fall back onto the rug whooping. Two seconds pass with @PADFOOT lying on his back laughing and @MOONY carefully lifting the candle off the blank map. Warm candlelight from below their faces, dark room. Vertical 9:16. No watermark, no visible phone or camera."),
(4,"peter got lost testing it","@PADFOOT (Peter wird beschrieben; auf dem Bild kommt Padfoot, nicht Prongs)",
"Candid first-person video from my own eye level, as if I just raised my old iPhone over my bag and hit record. "+Q+"an echoing stone cloister, footsteps, pigeons somewhere and a nervous voice. "+N+"The only people who speak are Peter and @PADFOOT, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A long stone cloister with arches and a window at the end, grey daylight. In the middle of the corridor "+PETER+" in a grey jumper and red-gold tie, holds a torn piece of parchment in both hands and stares up at the ceiling with his mouth open. Behind him @PADFOOT walks toward him in his black robe with his hands in his pockets, grinning. My brown bag is blurred large in the bottom of the frame. For the first two seconds Peter keeps staring at the ceiling and turns the parchment round, as if he heard me. Then he looks at the camera and says, lips moving: \"It said left. I went left. There's no left.\" He listens for two seconds as if I'm answering. @PADFOOT reaches him, takes the parchment out of his hands, turns it the right way up and holds it in front of Peter's face, then looks at the camera and says: \"He's been on the wrong floor for an hour.\" Peter looks at the parchment, looks up at the ceiling again and says: \"Oh. That's the third floor.\" @PADFOOT pats him on the shoulder and says to the camera: \"This is the fifth, Wormtail.\" Two seconds pass with @PADFOOT steering Peter toward the stairs by the shoulder and Peter still staring at the sheet. Flat grey daylight. Vertical 9:16. No watermark, no visible phone or camera."),
(5,"we needed the seventh floor","@PADFOOT, @PRONGS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone around the corner and hit record. "+Q+"whispering, a quill scratching on parchment against stone, slippers shuffling on flagstones and wind in a corridor. "+N+"The only people who speak are @PADFOOT and @PRONGS, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A dark stone corridor at night, cold moonlight from a window at the far end. @PADFOOT crouches against the wall in striped blue pyjamas and slippers, drawing on a sheet of parchment pinned to the stone with a quill, a candle, an ink bottle and loose sheets on the floor beside him. Next to him a pair of green striped pyjama trousers and slippers stands in mid-air with nothing above the waist, as if the top half of that person is invisible. My hand on the wall is blurred in the foreground. For the first two seconds @PADFOOT keeps drawing a line on the sheet and glances down the corridor, as if he heard me. Then he looks at the camera and whispers, lips moving: \"Shh. Last floor. Then we're done.\" He listens for two seconds as if I'm answering. The floating trousers shuffle a step, and @PRONGS's head and shoulders appear out of thin air above them as he pulls a shimmering cloak down, looks at the camera and whispers: \"The cloak only covers one of us. I called it.\" @PADFOOT hisses without looking up: \"You always call it.\" @PRONGS grins, pulls the cloak back over his head so only the trousers are left, and the trousers walk off down the corridor. @PADFOOT grabs the candle and the sheet and creeps after them, and the camera follows on tiptoe. Two seconds pass with only the floating trousers visible ahead in the moonlight. Cold blue light, very dark and grainy. Vertical 9:16. No watermark, no visible phone or camera."),
]
clips=[dict(n=n,title=t,attach="Startframe = Bild "+str(n)+", Referenzen: "+a,note="Folge 1",img=v) for (n,t,a,v) in sorted(V)]
WORLDS=[dict(key="mar",name="Marauders Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Marauders Folge 1 Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – MARAUDERS, FOLGE 1, VIDEO-PROMPTS\nOmni Flash 1.1, 10 Sekunden, 9:16. Für jeden Clip das Startframe-Bild mit derselben Caption nehmen, die genannten Referenzen anhängen und den VIDEO-Prompt eingeben.\nAlle Dialoge auf Englisch mit britischem Akzent. Der Kamerahalter spricht nie. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund. Personen stehen bei jeder Erwähnung als @NAME.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Marauders Folge 1: Video-Prompts zu den fertigen Startframes, nummeriert wie die Folge. Alle 9 Clips komplett.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('marauders-01-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
