import json, re
Q="2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with "
N="The person holding the camera never speaks and makes no sound. "
L="All dialogue is spoken in casual, natural German. The Snapchat caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. "
J="the boy in the green hoodie and red backwards cap"; NE="the blonde girl with the ponytail and denim jacket"
V=[
(1,"jonas says they live here",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"birds, wind in tall grass, a paper map rustling and someone chewing. "+N+"The only people who speak are "+J+" and "+NE+", and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A misty meadow at sunrise with a forest behind and golden light through the haze. "+J+" stands in tall grass holding an unfolded map with a big circle drawn on it, pointing out across the meadow. Next to him "+NE+" with a colourful backpack chews on a cereal bar, looking at the map without much interest. For the first two seconds "+J+" keeps pointing and "+NE+" keeps chewing, as if they heard me. Then "+J+" looks at the camera and says with lips moving: \"Hier. Genau hier. Ich hab's eingekreist.\" He listens for two seconds as if I'm answering. "+NE+" looks at the camera, still chewing, and says: \"Er hat den Kreis gestern Abend gemacht. Im Dunkeln.\" "+J+" says: \"Der Kreis ist richtig. Das Feld ist nur größer als gedacht.\" "+NE+" takes the map out of his hand, turns it the other way round, and hands it back. Two seconds pass with "+J+" staring at the map and "+NE+" walking off into the grass. Golden misty light. Vertical 9:16. No watermark, no visible phone or camera."),
(2,"fresh ones. apparently",
"Candid first-person video from my own eye level, as if I just crouched down and raised my old iPhone over the mud and hit record. "+Q+"a stream trickling, wet mud, birds and a Pikachu making small pika sounds. "+N+"The Pikachu never speaks, it only says pika and chu sounds. The only people who speak are "+J+" and "+NE+", and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A muddy bank beside a small forest stream. Close in the foreground a row of small four-toed animal tracks in the wet mud. "+J+" crouches with his hand flat on the mud next to the tracks, staring at them with a serious face very close to the lens. Behind him "+NE+" stands with a Pikachu sitting on top of her backpack, looking down. For the first two seconds "+J+" keeps staring at the tracks and touches one with a finger, as if he heard me. Then he looks at the camera and says with lips moving: \"Frisch. Maximal eine Stunde alt.\" He listens for two seconds as if I'm answering. "+NE+" looks at the camera and says: \"Woher willst du das wissen?\" "+J+" says: \"Man sieht das. Am Rand.\" The Pikachu jumps down from the backpack, walks straight through the tracks and leaves its own footprints on top. "+J+" looks at the ruined tracks, then at the camera, and says nothing. "+NE+" says: \"Jetzt sind sie noch frischer.\" Two seconds pass with the Pikachu sniffing at the water. Soft green forest light. Vertical 9:16. No watermark, no visible phone or camera."),
(3,"it smells sweet here",
"Candid first-person video from my own eye level, as if I just raised my old iPhone in the meadow and hit record. "+Q+"bees, wind in flowers, a Charmander chirping and a boy sniffing loudly. "+N+"The Charmander never speaks, it only makes small chirping sounds. The Pikachu never speaks, it only says pika sounds. The only people who speak are "+NE+" and "+J+", and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A sunny meadow full of purple and yellow wildflowers at the edge of a forest. "+NE+" stands with her eyes closed and her head tipped back, sniffing the air, one hand raised, a Pikachu sitting on her shoulder. Next to her "+J+" sniffs with a disgusted face. In front of them a Charmander with a flame on its tail sits among the flowers looking up. A big yellow flower is blurred in the foreground. For the first two seconds "+NE+" keeps sniffing with her eyes closed and "+J+" keeps grimacing, as if they heard me. Then "+NE+" opens her eyes, looks at the camera and says with lips moving: \"Riechst du das? Süß. Wie Honig.\" She listens for two seconds as if I'm answering. "+J+" looks at the camera and says: \"Ich riech nur Rudi.\" The Charmander turns round and its tail flame has singed a yellow flower, which is smoking. "+NE+" looks down at it, back at the camera, and says: \"Okay. Jetzt riecht es verbrannt.\" "+J+" picks up the Charmander and holds it away from the flowers. Two seconds pass with the Pikachu sniffing the air too. Warm sunlight. Vertical 9:16. No watermark, no visible phone or camera."),
(4,"step 1: find the sunny spot",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the grass and hit record. "+Q+"a quiet forest, insects, grass rustling and a boy whispering. "+N+"The Charmander never speaks, it only makes small chirping sounds. The only people who speak are "+J+" and "+NE+", and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A sunlit clearing in a pine forest with ferns. In the background "+J+" kneels in the grass with a finger on his lips, and in front of him a Charmander creeps forward on all fours toward a bright patch of sun. In the foreground "+NE+" lies flat on her back in the sun with her hands behind her head and her eyes closed. For the first two seconds "+J+" keeps his finger on his lips and the Charmander keeps creeping, and "+NE+" doesn't move at all, as if they heard me. Then "+J+" whispers toward the camera, lips moving: \"Pssst. Die kommen in die Sonne. Rudi lockt es an.\" He listens for two seconds as if I'm answering. "+NE+" says without opening her eyes: \"Ich lock es auch an. Ich bin auch in der Sonne.\" "+J+" hisses: \"Du schläfst.\" "+NE+" says: \"Das ist Taktik.\" The Charmander reaches the sunny patch, sits down in it and closes its eyes too. "+J+" looks at the camera and drops his hands. Two seconds pass with two of the three asleep in the sun. Dappled forest light. Vertical 9:16. No watermark, no visible phone or camera."),
(9,"we got it. jonas missed it",
"Candid first-person video from my own eye level, as if I just raised my old iPhone with the ball in my other hand and hit record. "+Q+"a forest clearing, two people cheering and a Charmander chirping. "+N+"The Charmander never speaks, it only makes small chirping sounds. The only people who speak are "+NE+" and "+J+", and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A sunny forest clearing with golden evening light between the trunks. Close to the lens my own open hand holds a scratched red and white ball, a little dust still drifting off it. Behind it, out of focus, "+NE+" stands with both fists in the air cheering, and "+J+" stands next to her with one hand on his head, a Charmander at his feet. For the first two seconds my hand keeps holding the ball still and "+NE+" keeps jumping, as if they heard me. Then "+NE+" looks at the camera and shouts with lips moving: \"Du hast es! Beim ersten Wurf!\" She listens for two seconds as if I'm answering. "+J+" looks at the camera and says: \"Ich hab dreimal geworfen. Dreimal.\" "+NE+" says: \"Zweimal einen Baum getroffen.\" "+J+" says: \"Der Baum stand im Weg.\" The Charmander chirps and pats "+J+"'s leg. "+NE+" runs toward the camera and the ball in my hand wobbles as she grabs my arm to look. Two seconds pass with "+J+" staring at the ball in my hand. Warm golden light. Vertical 9:16. No watermark, no visible phone or camera."),
(5,"there it is",
"Candid first-person video from my own eye level, as if I just crouched in the tall grass and raised my old iPhone and hit record. "+Q+"a quiet forest, insects, dry grass brushing the lens and a tiny snore. "+N+"The Bulbasaur never speaks, it only makes small sleepy grunting sounds. Nobody speaks in this clip, there is no voice at all. "+L+
"A sunlit forest floor seen through tall dry grass stalks that cross the frame out of focus. In a bright patch of sun a small blue-green Bulbasaur with a green bulb on its back lies flat on its belly, fast asleep, eyes closed. For the first two seconds nothing moves except the grass stalks swaying gently in front of the lens and the Bulbasaur's sides rising and falling. Then the camera creeps a little closer and lower, a stalk brushes across the lens, and the Bulbasaur's ear twitches. It grunts softly in its sleep, rolls half onto its side so the bulb tips, and its back leg kicks once. The camera stops moving. Two seconds pass with the Bulbasaur snoring in the sun and the grass swaying. Then it yawns wide without opening its eyes and settles again. Dappled golden light, soft focus. Vertical 9:16. No watermark, no visible phone or camera."),
(6,"rudi go",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the forest path and hit record. "+Q+"a forest, vines whipping through the air, a Charmander screeching, a boy shouting and a girl yelling. "+N+"The Bulbasaur never speaks, it only grunts and growls. The Charmander never speaks, it only screeches and chirps. The Pikachu never speaks, it only says pika sounds. The only people who speak are "+J+" and "+NE+", and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A forest path between tall trunks in warm evening light. In the foreground a Bulbasaur stands squarely on the path with two long green vines stretched out of its bulb. One vine is wrapped around "+J+", lifting him off the ground with his feet dangling, and the other around a screeching Charmander held up next to him. Behind them "+NE+" stands with a Pikachu on her shoulder, one arm stretched out in shock. For the first two seconds "+J+" dangles and kicks, the Charmander flails, and the Bulbasaur doesn't move, as if it heard me. Then "+J+" turns his head to the camera and shouts with lips moving: \"Rudi, Glut! Glut, mach Glut!\" He listens for two seconds as if I'm answering. The Charmander spits a tiny puff of flame that fizzles out, and "+NE+" looks at the camera and yells: \"Es hängt kopfüber, was soll es machen!\" "+J+" says: \"Dann lass mich runter, dann mach ich was!\" The Bulbasaur looks at the camera, grunts, and swings both of them gently from side to side. "+NE+" says: \"Ich glaub, es spielt.\" Two seconds pass with "+J+" swinging and the Pikachu watching from her shoulder. Warm evening light. Vertical 9:16. No watermark, no visible phone or camera."),
(7,"it used sleep powder",
"Candid first-person video from my own eye level, as if I just raised my old iPhone across the grass and hit record. "+Q+"a forest, a soft snore, a Charmander chirping and a girl talking through her sleeve. "+N+"The Bulbasaur never speaks, it only grunts. The Charmander never speaks, it only chirps. The only person who speaks is "+NE+", and she turns her face to the camera before speaking so her lips are visible moving with every word. "+L+
"A sunlit clearing with a faint blue-green glittering powder drifting in the air between the trees. "+J+" lies flat on his back in the grass with his mouth open, fast asleep. Next to his head a Charmander stands with both paws over its own nose. Behind them a Bulbasaur sits in the grass looking pleased with itself. On the right edge "+NE+" stands with her sleeve pressed over her nose and mouth, half cut off by the frame. For the first two seconds "+J+" keeps snoring and the powder keeps drifting, as if they heard me. Then "+NE+" looks at the camera and says through her sleeve, lips moving: \"Nicht einatmen. Nicht einatmen.\" She listens for two seconds as if I'm answering. She nudges "+J+" with her foot, nothing happens, and she says: \"Er hat gesagt, er hat einen Plan. Das war der Plan.\" The Charmander takes its paws off its nose, sniffs, yawns hugely and lies down against "+J+"'s shoulder. "+NE+" says: \"Okay. Jetzt sind es zwei.\" The Bulbasaur looks at the camera and blinks slowly. Two seconds pass with "+NE+" backing away out of the powder cloud. Dappled sunlight, glitter in the air. Vertical 9:16. No watermark, no visible phone or camera."),
(8,"my turn",
"Candid first-person video from my own eye level, as if I just raised my old iPhone with my left hand while throwing with my right and hit record. "+Q+"a forest, a ball whistling through the air, a thud, a snore from behind and a Bulbasaur grunting. "+N+"The Bulbasaur never speaks, it only grunts. Nobody speaks in this clip, there is no voice at all. "+L+
"A sunlit clearing with tall trunks. In the foreground my own right arm is stretched out, blurred with motion, having just thrown a red and white ball that hangs in the air in front of a Bulbasaur standing in the grass with its mouth open in surprise. In the background "+J+" lies curled up asleep in the grass. For the first two seconds the ball flies the last stretch and bounces off the Bulbasaur's forehead with a soft knock, and the Bulbasaur blinks. Then the ball drops into the grass, springs open with a flash of red light, and the Bulbasaur is pulled into it as a streak of light. The ball closes and lies in the grass, then wobbles once to the left, once to the right, and again. My arm lowers slowly into the frame. Behind, "+J+" snores and rolls over without waking. Two seconds pass with the ball still wobbling in the grass and the camera holding completely still. Dappled forest light. Vertical 9:16. No watermark, no visible phone or camera."),
]
clips=[dict(n=n,title=t,attach="Startframe = Bild "+str(n)+" („"+t+"“), keine Referenzen, Personen beschrieben",note="Wald",img=v) for (n,t,v) in sorted(V)]
WORLDS=[dict(key="pk",name="Pokémon Wald Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Pokémon Wald Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – POKÉMON, WALD-VIDEO, VIDEO-PROMPTS\nOmni Flash 1.1, 10 Sekunden, 9:16. Für jeden Clip das Startframe-Bild mit derselben Caption nehmen und den VIDEO-Prompt eingeben. Keine @-Referenzen, alle Personen sind so beschrieben, wie sie auf dem Startframe aussehen.\nAlle Dialoge auf Deutsch. Der Kamerahalter spricht nie. Pokémon machen nur Laute und sprechen nie menschliche Wörter. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Pokémon, Wald-Video: Jonas und Nele auf der Suche, ich fange am Ende. Video-Prompts zu den fertigen Startframes, in Story-Reihenfolge nummeriert. Alle 9 Clips komplett.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('pk-forest-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
