import json, re
S=("Candid first-person video from my own eye level, as if I just raised my old phone and hit record. Real live-action phone footage of real teenagers on a real dirt path between fields at the edge of a small German town, grey overcast morning, bikes lying in the grass. The Pokémon are realistic physical creatures standing in the real scene, NOT anime, NOT cartoon, NOT illustrated. "
"2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with {audio}. "
"The person holding the camera never speaks and makes no sound. {poke} The only people who speak are {speakers}, and each turns their face to the camera before speaking so their lips are visible moving with every word. All dialogue is spoken in casual, natural German. No caption, no text overlay, no bar on the video. "
"{scene} Vertical 9:16. No watermark, no visible phone or camera.")
SNOR="A huge Snorlax, a round dark blue-green Pokémon with a cream-coloured belly, tiny feet and closed eyes, lies flat on its back right across the path, blocking it completely, snoring deeply."
V=[
("he's been there since 6am",
 "wind over the fields, birds and a deep rumbling snore",
 "The Snorlax never speaks, it only snores.",
 "Sam, a boy with brown hair and a black rain jacket",
 SNOR+" Sam, a boy with brown hair and a black rain jacket, stands next to the Snorlax's belly with a bucket at his feet in which a Magikarp flops weakly, scratching his head. For the first two seconds Sam keeps staring at the Snorlax and pokes its belly with one finger, it doesn't react, as if he heard me. Then he turns to the camera and says with lips moving: \"Seit sechs. Ich hab schon alles probiert.\" He listens for two seconds as if I'm answering, then shrugs and says: \"Ich hab's angeschrien. Ich hab ihm Brot angeboten. Nichts.\" He kicks the Snorlax's foot gently, the snore gets louder, and he looks back at the camera: \"Die anderen kommen gleich. Jonas hat angeblich einen Plan.\" Two seconds pass while he looks down the path and waves at someone in the distance."),
("jonas has a plan",
 "a small crackling flame, a snore and a boy laughing nervously",
 "The Snorlax never speaks, it only snores. The Charmander never speaks, it only makes small chirping sounds.",
 "Jonas, a boy with a red backwards cap and a green hoodie, and Sam, a boy with a black rain jacket",
 SNOR+" Jonas, a boy with a red backwards cap and a green hoodie, kneels at the Snorlax's foot holding his Charmander, a small orange lizard Pokémon with a flame on its tail, whose tail flame he is holding close to the Snorlax's toes. Sam stands behind him with his arms crossed. For the first two seconds Jonas waves the tail flame under the toes and the Snorlax only wiggles its foot and snores, as if he heard me. Then Jonas looks over his shoulder at the camera and says with lips moving: \"Warte, warte. Das dauert.\" He listens for two seconds as if I'm answering, then the sleeve of his hoodie catches fire, he yelps, slaps it out on the grass and says: \"Nichts passiert. Alles gut.\" Sam looks at the camera and says: \"Das war's mit dem Plan.\" The Charmander chirps and hides its face. Two seconds pass while Jonas checks his burnt sleeve and the Snorlax snores on."),
("bo tried",
 "a crackle of electricity, a snore and a girl sighing",
 "The Snorlax never speaks, it only snores. The Pikachu never speaks, it only says pika and chu sounds.",
 "Nele, a girl with a blonde ponytail and a denim jacket",
 SNOR+" Nele, a girl with a blonde ponytail and a denim jacket, stands beside it with her Pikachu, a small yellow Pokémon with red cheeks and a lightning-bolt tail, which stands on the Snorlax's belly with sparks in its cheeks. For the first two seconds the Pikachu releases a small crackling shock into the belly, the Snorlax's belly fur stands straight up and it keeps snoring, and Nele stares, as if she heard me. Then she looks at the camera and says with lips moving: \"Das war die volle Ladung. Guck dir das an.\" She listens for two seconds as if I'm answering, then says: \"Er hat sich nicht mal bewegt. Bo ist beleidigt.\" The Pikachu sits down on the belly with its back to everyone, ears flat, and says a sulky chu. Nele picks it up, looks at the camera and says: \"Wer hat noch Ideen?\" Two seconds pass while the Pikachu steals a biscuit from her pocket."),
("lukas gave up",
 "a snore, a second softer snore and wind over the fields",
 "The Snorlax never speaks, it only snores. The Psyduck never speaks, it only says psy sounds.",
 "Lukas, a boy in a grey hoodie with the hood up",
 SNOR+" Leaning against the Snorlax's side with his eyes closed sits Lukas, a boy in a grey hoodie with the hood up, fast asleep, and next to him a Psyduck, a yellow duck Pokémon holding its head, also asleep. For the first two seconds neither of them moves, both snore quietly in time with the Snorlax, as if they heard me and ignored it. Then Lukas opens one eye, looks at the camera and mumbles with lips moving: \"Ich bewache ihn.\" He listens for two seconds as if I'm answering, then says without moving: \"Falls er aufwacht, bin ich der Erste, der es merkt.\" The Psyduck wakes up, looks around confused, says psy and falls asleep again. Lukas pulls his hood lower over his face and says: \"Weck mich, wenn was passiert.\" Two seconds pass while all three snore together."),
("sam tried being nice",
 "a snore, a bucket sloshing and a boy talking softly",
 "The Snorlax never speaks, it only snores. The Magikarp never speaks, it only flops and splashes.",
 "Sam, a boy with brown hair and a black rain jacket",
 SNOR+" Sam, a boy with brown hair and a black rain jacket, crouches at the Snorlax's head holding an apple in front of its nose, his bucket with a flopping Magikarp beside him. For the first two seconds he wiggles the apple under the Snorlax's nose and its nostrils twitch but it keeps snoring, as if he heard me. Then he looks at the camera and says with lips moving: \"Ich rede einfach nett mit ihm. Das funktioniert immer.\" He listens for two seconds as if I'm answering, then turns back to the Snorlax and says softly: \"Hey, Großer. Willst du vielleicht aufstehen?\" The Snorlax rolls half over in its sleep, its arm lands on the bucket, the Magikarp flops out onto the grass and Sam scrambles to catch it. He looks back at the camera holding the wet fish and says: \"Okay. Es hat gefühlt funktioniert.\" Two seconds pass while he puts the Magikarp back in the bucket."),
("mira is not helping",
 "a snore, a Jigglypuff taking a deep breath and several people shouting no",
 "The Snorlax never speaks, it only snores. The Jigglypuff never speaks, it only hums and sings wordless notes.",
 "Mira, a girl with long brown hair, a red beanie and a navy rain jacket, and Jonas, a boy with a red backwards cap",
 SNOR+" Mira, a girl with long brown hair, a red beanie and a navy rain jacket, stands next to it with a completely blank face while a Jigglypuff, a round pink Pokémon with big blue eyes, climbs onto the Snorlax's belly and inflates itself, taking a huge breath to sing. Jonas, a boy with a red backwards cap, and two other teenagers run toward it in the background with their arms out. For the first two seconds Mira just stares at the camera without any expression while the Jigglypuff keeps inflating and the others shout in the background, as if she heard me. Then she says flatly, lips moving: \"Ich kann nichts machen. Es folgt mir nur.\" She listens for two seconds as if I'm answering, then says: \"Wenn es singt, schlafen alle. Auch du.\" Jonas reaches the belly, looks at the camera and yells: \"Halt es auf, halt es auf!\" The Jigglypuff opens its mouth and hums the first soft note, and everyone in the background slows down. Mira says: \"Zu spät.\" Two seconds pass while the camera starts to tilt down slowly."),
("everyone's asleep now",
 "a snore, several softer snores, a felt-tip marker squeaking and wind",
 "The Snorlax never speaks, it only snores. The Jigglypuff never speaks, it only hums and giggles.",
 "Mira, a girl with long brown hair, a red beanie and a navy rain jacket",
 SNOR+" All around it on the grass lie Jonas, Nele, Lukas, Sam and their Pokémon, fast asleep in a heap, with black marker scribbles on their faces, and the Jigglypuff sits on Jonas's chest drawing a moustache on him with a marker. Mira, a girl with long brown hair, a red beanie and a navy rain jacket, is the only one awake and stands in the middle of it with her hands in her pockets. For the first two seconds she looks at the sleeping pile and then at the camera without any expression, as if she heard me. Then she says flatly, lips moving: \"Ich schlaf nie ein. Ich hab mich dran gewöhnt.\" She listens for two seconds as if I'm answering, then nods at the Jigglypuff and says: \"Das macht es immer danach. Ich weiß auch nicht, warum.\" The Jigglypuff finishes the moustache, giggles, and moves on to Nele. Mira looks at the camera and says: \"Yuna ist noch nicht da. Die hat eine Idee, hat sie gesagt.\" Two seconds pass while she steps over Lukas and sits down on the Snorlax's foot."),
("yuna wants to fight it",
 "a water jet hitting something, a snore that stops and a girl shouting",
 "The Snorlax never speaks, it only snores and grunts. The Squirtle never speaks, it only says squirt sounds.",
 "Yuna, a girl with a black braid and a yellow raincoat",
 SNOR+" Yuna, a girl with a black braid and a yellow raincoat, stands in a wide fighting stance in front of it with her Squirtle, a small blue turtle Pokémon, which is spraying a jet of water straight into the Snorlax's face. The others sit up sleepily in the background with marker on their faces. For the first two seconds the water jet hits the Snorlax's face and its snore stutters, and Yuna doesn't take her eyes off it, as if she heard me. Then she looks at the camera and says with lips moving: \"Vierzig Minuten. Ich hab Zeit.\" She listens for two seconds as if I'm answering, then points at the Snorlax and shouts: \"Kai, nochmal!\" The Squirtle sprays again, and the Snorlax slowly opens one eye and looks straight at her. Yuna freezes, looks at the camera, and says quietly: \"Okay. Es ist wach.\" The Snorlax grunts deeply and starts to sit up, the ground shakes, and the camera stumbles back a step. Two seconds pass with everyone staring up at it."),
("it just wanted breakfast",
 "loud chewing, wrappers rustling, a boy groaning and people laughing",
 "The Snorlax never speaks, it only chews and grunts happily. The Pikachu never speaks, it only says pika sounds.",
 "Sam, a boy with brown hair and a black rain jacket, and Nele, a girl with a blonde ponytail and a denim jacket",
 "The huge Snorlax, a round dark blue-green Pokémon with a cream-coloured belly, now sits upright at the side of the dirt path with its eyes half open, holding Sam's open backpack upside down over its mouth and pouring the whole contents of sandwiches, biscuits and crisps into it, chewing loudly. The path is free. Sam, a boy with brown hair and a black rain jacket, stands in front of it with his arms hanging down. Nele, a girl with a blonde ponytail and a denim jacket, stands next to him with her Pikachu, which is quietly eating a biscuit it stole from the pile. For the first two seconds Sam just watches his lunch disappear, as if he heard me. Then he looks at the camera and says with lips moving: \"Das waren meine Brote für die ganze Woche.\" He listens for two seconds as if I'm answering, then says: \"Es wollte einfach nur frühstücken. Sechs Stunden. Für ein Frühstück.\" Nele looks at the camera, laughing, and says: \"Der Weg ist frei. Wir kommen nur drei Stunden zu spät.\" The Snorlax burps, pats its belly and lies back down across the path with a thud. Sam looks at the camera and says nothing, just closes his eyes. Two seconds pass while the Pikachu finishes the biscuit."),
]
clips=[dict(n=i,title=t,attach="Kein Startframe, Text-zu-Video",note="Video 1",img=S.format(audio=a,poke=p,speakers=sp,scene=sc)) for i,(t,a,p,sp,sc) in enumerate(V,1)]
WORLDS=[dict(key="pk",name="Pokémon Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Pokémon Relaxo Video</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – POKÉMON, EIN VIDEO AUS 9 SNAPS (RELAXO AUF DEM WEG)\n10 Sekunden pro Clip, 9:16, Text-zu-Video ohne Startframe, in dieser Reihenfolge.\nAlle Dialoge auf Deutsch. Der Kamerahalter spricht nie. Pokémon machen nur Laute und sprechen nie menschliche Wörter. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund. Kein Caption-Balken, Text kommt später im Schnitt.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Pokémon, ein zusammenhängendes Video aus 9 Snaps: ein Relaxo liegt quer über dem Schulweg. Ohne Startframe, ohne Caption-Balken. Die Caption oben ist nur der Titel für deinen Schnitt.')
open('pk-snorlax.html','w',encoding='utf-8').write(h)
print(len(clips))
