import json, re
Q="2015 smartphone video quality: soft focus, visible noise and slight compression, motion blur, uneven handheld framing that shakes in my hand, people cut off at the edges, no flash, no filter, audio like a phone microphone with "
N="The person holding the camera never speaks and makes no sound. "
L="All dialogue is spoken in casual, natural German. The Snapchat caption bar with the white text in the photo stays exactly as it is on screen for the whole video, like a fixed overlay. "
SN="The huge Snorlax lying on its back across the dirt path never speaks, it only snores, grunts and chews. "
V=[
(2,"jonas has a plan","@JONAS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"wind over foggy fields, a deep rumbling snore, a small crackling flame and a boy yelping. "+N+SN+"The Charmander never speaks, it only makes small chirping sounds. The only person who speaks is @JONAS, and he turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A foggy dirt path between fields at dawn. The huge Snorlax lies on its back across the path with its mouth open, snoring, one giant foot toward the camera. @JONAS in a green hoodie and a red backwards cap crouches at the foot holding his Charmander by the belly and pressing its tail flame against the Snorlax's toes, a thin line of smoke already rising from his own sleeve. For the first two seconds @JONAS keeps waving the flame under the toes and the Snorlax only wiggles its foot and snores on, as if he heard me. Then @JONAS looks over his shoulder at the camera and says with lips moving: \"Warte, warte. Das dauert.\" He listens for two seconds as if I'm answering. Then his sleeve catches fire, he yelps, drops the Charmander into the grass and slaps the sleeve out on the wet ground, then looks at the camera and says: \"Nichts passiert. Alles gut.\" The Charmander chirps and hides behind his leg. @JONAS looks at the Snorlax's foot, which hasn't moved, and says: \"Okay. Plan B.\" Two seconds pass with @JONAS staring at his burnt sleeve and the Snorlax snoring. Flat grey foggy light. Vertical 9:16. No watermark, no visible phone or camera."),
(6,"mira is not helping","@MIRA, @NELE, @JONAS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"wind, a snore, a Jigglypuff taking a huge breath and three people shouting nein. "+N+SN+"The Jigglypuff never speaks, it only inflates, hums and sings wordless notes. The only people who speak are @MIRA and @NELE, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A dirt path between fields at sunrise, golden mist. In the foreground @MIRA in a red beanie and a dark rain jacket stands with her arms hanging down and a completely blank face. In front of the Snorlax's belly a Jigglypuff sits on the path with its eyes closed, inflating itself to sing. Behind them @NELE with blonde hair, @JONAS in a red cap and a boy in black run toward the Jigglypuff with their arms stretched out. For the first two seconds @MIRA just stares past the camera without any expression while the Jigglypuff keeps inflating and the others keep running, as if she heard me. Then @MIRA looks at the camera and says flatly, lips moving: \"Ich kann nichts machen. Es folgt mir nur.\" She listens for two seconds as if I'm answering, then says: \"Wenn es singt, schlafen alle. Auch du.\" @NELE reaches the Jigglypuff, looks at the camera and yells: \"Halt es auf, halt es auf!\" The Jigglypuff opens its mouth and hums the first soft note, and @NELE, @JONAS and the boy in black slow down and sway. @MIRA says: \"Zu spät.\" Two seconds pass while the camera slowly tilts down toward the grass. Warm golden light through mist. Vertical 9:16. No watermark, no visible phone or camera."),
(7,"everyone's asleep now","@MIRA",
"Candid first-person video from my own eye level, as if I just raised my old iPhone from the grass and hit record. "+Q+"a deep snore, several softer snores, a felt-tip marker squeaking and a Jigglypuff giggling. "+N+SN+"The Jigglypuff never speaks, it only hums and giggles. The Pokémon on the ground never speak, they only breathe and snore. The only person who speaks is @MIRA, the girl with long brown hair leaning against the Snorlax, and she turns her face to the camera before speaking so her lips are visible moving with every word. "+L+
"A dirt path between fields at sunrise, golden mist. Around the Snorlax on the grass lie five people fast asleep in a heap: a boy in a red cap and green hoodie, a boy in black with a small Pidgey asleep on his shoulder, a girl in a red beanie hugging a sleeping Charmander, a girl in a yellow raincoat with a sleeping Squirtle, a sleeping Pikachu. Only @MIRA, a girl with long brown hair in a grey top, is awake, leaning against the Snorlax's belly with her chin in her hand, and beside her a Jigglypuff sits on the belly holding a black marker. For the first two seconds @MIRA looks at the sleeping pile and then at the camera without any expression, as if she heard me. Then she says flatly, lips moving: \"Ich schlaf nie ein. Ich hab mich dran gewöhnt.\" She listens for two seconds as if I'm answering. The Jigglypuff slides down off the belly, waddles over to the boy in the red cap and starts drawing a moustache on his face with the marker. @MIRA nods at it and says: \"Das macht es immer danach. Ich weiß auch nicht, warum.\" She listens again, then says: \"Yuna wollte es bekämpfen. Die schläft auch.\" Two seconds pass with the Jigglypuff giggling and moving on to the next face and @MIRA not moving at all. Warm golden light. Vertical 9:16. No watermark, no visible phone or camera."),
(8,"yuna wants to fight it","@YUNA, @SAM",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"a jet of water hitting fur, a snore that stutters and stops, a girl shouting and a boy groaning. "+N+SN+"The Squirtle never speaks, it only says squirt sounds and sprays water. The only people who speak are @YUNA and @SAM, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A dirt path between fields at sunrise, golden mist. @YUNA in a yellow raincoat and yellow boots stands in a wide stance pointing straight at the Snorlax, her Squirtle beside her spraying a hard jet of water into the Snorlax's open mouth and face. Behind her @SAM, a red-haired boy in a school blazer, scratches his head, and two others stand with their faces in their hands. For the first two seconds the water keeps hitting the Snorlax's face and its snore stutters, and @YUNA doesn't take her eyes off it, as if she heard me. Then @YUNA looks at the camera and says with lips moving: \"Vierzig Minuten. Ich hab Zeit.\" She listens for two seconds as if I'm answering, then points harder and shouts: \"Kai, nochmal!\" The Squirtle sprays again, and the Snorlax slowly opens one eye and looks straight at her. @SAM looks at the camera and says quietly: \"Oh nein.\" @YUNA freezes, looks at the camera and says: \"Okay. Es ist wach.\" The Snorlax grunts deeply and starts to sit up, the ground shakes, and the camera stumbles back a step. Two seconds pass with everyone staring up at it. Warm golden light. Vertical 9:16. No watermark, no visible phone or camera."),
(9,"it just wanted breakfast","@SAM, @NELE",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"loud chewing, wrappers rustling, a boy groaning, people laughing and two Pidgeys chirping. "+N+"The Snorlax never speaks, it only chews and grunts happily. The Pidgeys never speak, they only chirp and peck. The only people who speak are @SAM and @NELE, and each turns their face to the camera before speaking so their lips are visible moving with every word. "+L+
"A dirt path between fields in blue dusk fog. The huge Snorlax now sits upright at the side of the path with its eyes half closed, stuffing a sandwich into its mouth, an open backpack and snack wrappers scattered all over the grass in front of it. The path is free. @SAM, a red-haired boy in a school blazer, stands in front of it looking down into his empty bag. Around them stand @NELE with blonde hair and four others, staring at the Snorlax. Two Pidgeys peck at the crumbs, one right in the foreground. For the first two seconds @SAM just stares into his empty bag and the Snorlax keeps chewing, as if he heard me. Then @SAM looks at the camera and says with lips moving: \"Das waren meine Brote für die ganze Woche.\" He listens for two seconds as if I'm answering, then says: \"Es wollte einfach nur frühstücken. Sechs Stunden. Für ein Frühstück.\" @NELE looks at the camera, laughing, and says: \"Der Weg ist frei. Wir kommen nur drei Stunden zu spät.\" The Snorlax burps, pats its belly and lies back down across the path with a thud, and everyone groans. @SAM looks at the camera, says nothing, and closes his eyes. Two seconds pass with the Pidgey in the foreground finishing a crisp. Cold blue foggy light. Vertical 9:16. No watermark, no visible phone or camera."),
(1,"he's been there since 6am","@SAM",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"wind over foggy fields, birds, a deep rumbling snore and water sloshing in a bucket. "+N+SN+"The Magikarp never speaks, it only flops and splashes. The only person who speaks is @SAM, and he turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A foggy dirt path between fields at dawn. The huge Snorlax lies on its back across the path with its mouth open, snoring. @SAM, a red-haired boy in a school blazer with a backpack, stands beside its belly with one hand in his hair, looking down at the Snorlax, a plastic bucket with a Magikarp in it at his feet. For the first two seconds @SAM keeps staring at the Snorlax and pokes its belly with one finger, it doesn't react, as if he heard me. Then he turns to the camera and says with lips moving: \"Seit sechs. Ich hab schon alles probiert.\" He listens for two seconds as if I'm answering, then shrugs and says: \"Ich hab's angeschrien. Ich hab ihm Brot angeboten. Nichts.\" He nudges the Snorlax's foot with his shoe, the snore gets louder, the Magikarp flops in the bucket, and he looks back at the camera: \"Die anderen kommen gleich. Jonas hat angeblich einen Plan.\" Two seconds pass while @SAM looks down the foggy path and waves at someone in the distance. Flat grey foggy light. Vertical 9:16. No watermark, no visible phone or camera."),
(3,"bo tried","@NELE",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"wind, a crackle of electricity, a snore and a girl giggling. "+N+SN+"The Pikachu never speaks, it only says pika and chu sounds. The only person who speaks is @NELE, and she turns her face to the camera before speaking so her lips are visible moving with every word. "+L+
"A foggy dirt path between fields. The huge Snorlax lies on its back across the path, and on top of its belly stands a Pikachu with sparks crackling in its cheeks. In front of the belly @NELE with a blonde ponytail, a denim jacket and a colourful backpack stands sideways with her hand over her mouth, giggling. For the first two seconds the Pikachu releases a crackling shock into the belly, the fur stands straight up around it and the Snorlax keeps snoring, and @NELE giggles harder, as if she heard me. Then @NELE looks at the camera and says with lips moving: \"Das war die volle Ladung. Guck dir das an.\" She listens for two seconds as if I'm answering, then says: \"Er hat sich nicht mal bewegt. Bo ist beleidigt.\" The Pikachu sits down on the belly with its back to everyone, ears flat, and says a sulky chu. @NELE reaches up, lifts it off the belly, looks at the camera and says: \"Wer hat noch Ideen?\" Two seconds pass while the Pikachu digs a biscuit out of her jacket pocket. Flat grey light. Vertical 9:16. No watermark, no visible phone or camera."),
(4,"lukas gave up","@LUKAS",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"a deep snore, a second softer snore, a duck-like sigh and wind over the fields. "+N+SN+"The Psyduck never speaks, it only says psy sounds. The only person who speaks is @LUKAS, and he turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A foggy dirt path between fields. The huge Snorlax lies on its back across the path, and leaning against its belly on the grass sits @LUKAS in a dark blazer with his backpack as a pillow, eyes closed, hands folded on his stomach, fast asleep. Next to him a Psyduck sits with its hands on its head, also asleep. For the first two seconds neither of them moves, both snore quietly in time with the Snorlax, as if they heard me and ignored it. Then @LUKAS opens one eye, looks at the camera and mumbles with lips moving: \"Ich bewache ihn.\" He listens for two seconds as if I'm answering, then says without moving: \"Falls er aufwacht, bin ich der Erste, der es merkt.\" The Psyduck wakes up, looks around confused, says psy and falls asleep again against his shoulder. @LUKAS pulls his collar up and says: \"Weck mich, wenn was passiert.\" Two seconds pass while all three snore together. Flat grey foggy light. Vertical 9:16. No watermark, no visible phone or camera."),
(5,"sam tried being nice","@SAM (auf dem Bild der dunkelhaarige Junge in der schwarzen Jacke)",
"Candid first-person video from my own eye level, as if I just raised my old iPhone on the path and hit record. "+Q+"birds, a snore, a bucket tipping over and a fish flopping in wet grass. "+N+SN+"The Magikarp never speaks, it only flops and splashes. The only person who speaks is @SAM, and he turns his face to the camera before speaking so his lips are visible moving with every word. "+L+
"A dirt path between green fields under a clear morning sky. The huge Snorlax lies on its back across the path, snoring. @SAM, a dark-haired boy in a black jacket, crouches beside its belly holding out a red apple with a friendly smile, while behind him a plastic bucket has just tipped over and a Magikarp is jumping out of it in a splash of water. For the first two seconds @SAM keeps holding the apple toward the Snorlax's face and the Magikarp lands in the grass and flops, as if he heard me. Then @SAM looks at the camera and says with lips moving: \"Ich rede einfach nett mit ihm. Das funktioniert immer.\" He listens for two seconds as if I'm answering, then turns back to the Snorlax and says softly: \"Hey, Großer. Willst du vielleicht aufstehen?\" The Snorlax rolls half over in its sleep, its arm flops onto the path right next to him, and @SAM scrambles backwards and grabs the flopping Magikarp with both hands. He looks at the camera holding the wet fish and says: \"Okay. Es hat gefühlt funktioniert.\" Two seconds pass while he puts the Magikarp back into the bucket and sets it upright. Clear morning light. Vertical 9:16. No watermark, no visible phone or camera."),
]
clips=[dict(n=n,title=t,attach="Startframe = Bild "+str(n)+", Referenzen: "+a,note="Relaxo",img=v) for (n,t,a,v) in sorted(V)]
WORLDS=[dict(key="pk",name="Pokémon Relaxo Videos",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('/home/user/claude-trade/snaps/prompts/batch-02-hp-videos.html',encoding='utf-8').read()
h=h.replace('<title>Wizarding Videos 02</title>','<title>Pokémon Relaxo Videos</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – POKÉMON, RELAXO-VIDEO, VIDEO-PROMPTS\nOmni Flash 1.1, 10 Sekunden, 9:16. Für jeden Clip das Startframe-Bild mit derselben Caption nehmen, die genannten Referenzen anhängen und den VIDEO-Prompt eingeben.\nAlle Dialoge auf Deutsch. Der Kamerahalter spricht nie. Pokémon machen nur Laute und sprechen nie menschliche Wörter. Jeder Satz gehört zu der sichtbaren Person, die im Prompt genannt ist, mit sichtbar bewegtem Mund. Personen stehen bei jeder Erwähnung als @NAME.\n`;", h, flags=re.S)
h=h.replace('Wizarding World Batch 02, alle 18 Video-Prompts. Startframe ist jeweils das fertige Bild mit derselben Caption.','Pokémon Relaxo-Video: Video-Prompts zu den fertigen Startframes, nummeriert wie die Reihenfolge im Video. Alle 9 Clips komplett.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","Clip ${String(c.n).padStart(2,'0')}")
open('pk-snorlax-videos.html','w',encoding='utf-8').write(h)
print(len(clips))
