import sys, json, re
sys.path.insert(0,'.')
from data import PK_IMG, G
GEN="a Gengar, a round dark-purple ghost Pokémon with short velvety fur, small pointed ears, spiky back, glowing red eyes and a huge wide toothy grin, photographed like a real creature"
LUC="a Lucario, a tall blue-and-black jackal-like Pokémon standing upright on two legs with real fur, a cream chest, black mask markings and pointed ears, photographed like a real animal"
S = [
("he followed me home","with a cold blue cast from a phone screen and street light, dark","A dark teenage bedroom at night, posters on the wall, a messy bed, my own duvet blurred in the foreground as if I am lying in bed. In the half-open wardrobe door across the room, only the glowing red eyes and the wide white grin of "+GEN+" are visible, peeking out of the darkness, the rest of it melting into the shadow."),
("breakfast with a ghost","with a warm cast from morning light through a kitchen window","A small ordinary kitchen in the morning, a table with cereal boxes, a carton of milk and a bowl. Right across the table from me, "+GEN+" sits on a kitchen chair with its face buried in my cereal bowl, milk dripping from its grin, one hand holding the spoon. On the windowsill behind it, a real-looking cream-coloured Meowth cat Pokémon sits watching with narrowed eyes."),
("asking around","with a cold grey cast, blown-out overcast sky","A small-town market square with a fruit stall and cobblestones. Right in front of me, "+GEN+" floats at eye level holding up a crumpled hand-drawn crayon picture of a blue jackal Pokémon toward a confused old man in a flat cap, who leans back with raised eyebrows. At the old man's feet, a real-looking orange-and-black striped Growlithe puppy Pokémon growls at the Gengar with its fur up."),
("he says it's this way","with a cold green cast, dark forest, blown-out sky between the trees","A muddy path leading into a dark pine forest, mist between the trees. Right in front of me, "+GEN+" hovers at the edge of the path with its back half turned to me, pointing one clawed hand deep into the darkest part of the forest, grinning back over its shoulder. On a low branch above it, a small round brown Hoothoot owl Pokémon with one leg tucked up stares at the camera."),
("train ride","with a warm cast from a reading light, blown-out window","Inside an old regional train with worn seats. In the row in front of me, "+GEN+" has sunk halfway through the back of the seat so only its head, grin and one arm stick out toward the aisle, its red eyes fixed on the passenger across the aisle. That passenger, a woman in a raincoat, is frozen with a sandwich halfway to her mouth, while a round pink Jigglypuff on her lap stares at the Gengar with huge eyes."),
("not quite","with a cold grey cast, light rain","A wet playground with a climbing frame and puddles. Right in front of me, "+GEN+" hugs a small blue-and-black Riolu, a knee-high jackal-like puppy Pokémon with real fur, so tightly that the Riolu's arms stick out sideways and its face looks squashed and alarmed, while the Gengar grins triumphantly at the camera as if it has found what we were looking for."),
("found him","with a cold blue cast from mist and water, blown-out sky","A rocky riverbank below a tall waterfall, mist in the air, wet boulders. On a flat rock in the middle of the river, "+LUC+" sits cross-legged with its eyes closed, meditating perfectly still, water spraying around it. In the bottom corner of the frame, close to the camera and out of focus, "+GEN+" is creeping up on the rock on all fours with an enormous grin, a finger raised to its mouth."),
("they get along","with a warm cast from late afternoon sun, lens flare","A wooden picnic table by a lake in warm afternoon light. Across the table from me, "+LUC+" and "+GEN+" are arm-wrestling, both straining, the Lucario with a fierce focused face and the Gengar cheating by resting its second arm on the table too, grinning. On the end of the bench, a yellow Psyduck with real feathers watches with its hands on its head."),
("say hi to [NAME]","with a warm orange cast from sunset, lens flare, slightly overexposed","A grassy hilltop at sunset, the town far below, warm orange light. Right in front of me, very close, "+GEN+" and "+LUC+" stand side by side looking straight into the camera: the Gengar waving one clawed hand with its widest grin, the Lucario with its arms crossed giving a small, serious nod and a thumbs up. Behind them a flock of Pidgey birds crossing the orange sky."),
]
clips=[dict(n=i,title=t,attach="keine Figuren, nur Stil-Snaps",note="Gengar & Lucario",img=PK_IMG.format(cast=c,scene=s,caption=t)) for i,(t,c,s) in enumerate(S,1)]
WORLDS=[dict(key="gl",name="Gengar & Lucario",clips=clips)]
d=json.dumps(WORLDS,ensure_ascii=False).replace('</','<\\/')
h=open('batch-02.html',encoding='utf-8').read()
h=h.replace('<title>Snap Startframes 02</title>','<title>Gengar Sucht Lucario</title>')
h=re.sub(r"const DATA = .*?;\nconst INSTR", lambda m:"const DATA = "+d+";\nconst INSTR", h, flags=re.S)
h=re.sub(r"const INSTR = \(name\)=>`.*?`;", lambda m: "const INSTR = (name)=>`ANLEITUNG FÜR FLOW – POKÉMON SPEZIAL: GENGAR SUCHT LUCARIO (ein Video, 9 Clips)\nDie angehängten Referenz-Snaps sind die Stilvorlage für ALLE Bilder: gleiche Bildqualität, gleiche Farben, gleicher Caption-Balken. Alles ist ein echtes Handyfoto, nie Illustration, Anime, CGI oder Render. Die Pokémon sind wie echte Tiere fotografiert.\nKeine Figuren-Referenzen nötig. Gengar sieht in allen Clips gleich aus, Lucario ebenfalls. Andere Pokémon tauchen pro Clip nur einmal auf.\nNano Banana 2, 9:16. Pro Clip den BILD-Prompt eingeben, Stil-Referenzen anhängen, Ergebnis speichern. Die Video-Prompts kommen im zweiten Schritt, nachdem die Bilder fertig sind. In Clip 9 [NAME] durch den Namen des Zuschauers ersetzen.\n`;", h, flags=re.S)
h=h.replace('Batch 02: zwei Videos à 9 Clips, nur Bild-Prompts. Bilder erzeugen, mir mit Clip-Nummer schicken, dann kommen die Video-Prompts.','Ein Video, 9 Clips: Ich bin mit Gengar unterwegs, wir suchen Lucario, am Ende grüßen beide den Zuschauer. In Clip 9 [NAME] ersetzen. Bilder erzeugen, mir mit Clip-Nummer schicken, dann kommen die Video-Prompts.')
h=h.replace("${c.note.replace('Video ','V')}·${String(c.n).padStart(2,'0')}","${String(c.n).padStart(2,'0')}")
open('gengar.html','w',encoding='utf-8').write(h)
print(len(clips))
