"""Command line entry point."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .config import ConfigError, load_config
from .state import Store

DEFAULT_CONFIG = Path(__file__).resolve().parent.parent / "config.toml"


def _add_common(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--config", type=Path, default=DEFAULT_CONFIG,
        help=f"path to config.toml (default: {DEFAULT_CONFIG})",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="povflow",
        description="Generate first-person POV shorts and a matching voice-over script.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    run = sub.add_parser("run", help="produce episodes")
    _add_common(run)
    run.add_argument("-n", "--count", type=int, default=1, help="episodes to produce")
    run.add_argument(
        "--dry-run", action="store_true",
        help="plan everything and write the scripts, generate no video, spend nothing",
    )
    run.add_argument(
        "--keep-intermediates", action="store_true",
        help="keep the per-clip working files after assembly",
    )

    asm = sub.add_parser(
        "assemble", help="stitch clips you generated by hand into a finished cut"
    )
    _add_common(asm)
    asm.add_argument("folder", type=Path, help="episode folder containing shots/")
    asm.add_argument("--keep-intermediates", action="store_true")

    costs = sub.add_parser("costs", help="show rates, budget caps and month-to-date spend")
    _add_common(costs)

    history = sub.add_parser("history", help="list produced episodes")
    _add_common(history)
    history.add_argument("-n", "--count", type=int, default=20)

    return parser


def cmd_run(args: argparse.Namespace) -> int:
    from .pipeline import run_batch

    cfg = load_config(args.config)
    store = Store(cfg.state_db)

    if args.dry_run:
        print("DRY RUN — no video is generated and nothing is charged.\n")
    elif cfg.is_manual:
        credits = cfg.credits_per_episode * args.count
        print(f"Planning {args.count} episode(s), {cfg.episode_seconds}s each.")
        print(f"You generate the clips in Flow: about {credits:.0f} credits "
              f"(~{cfg.eur_per_credit * credits:.2f} EUR) in total.\n")
    else:
        estimate = cfg.usd_per_episode * args.count
        print(f"About to generate {args.count} episode(s), "
              f"{cfg.episode_seconds}s each, estimated ${estimate:.2f} total.\n")

    results = run_batch(
        cfg, store, args.count, dry_run=args.dry_run,
        keep_intermediates=args.keep_intermediates,
    )

    if not results:
        print("\nNo episodes produced.")
        return 1

    print(f"\n{'=' * 60}")
    for result in results:
        print(f"\n{result.concept.title}")
        print(f"  folder: {result.directory}")
        if result.video_path:
            print(f"  video:  {result.video_path.name}  (silent cut, record over this)")
        elif result.dry_run:
            print("  video:  none (dry run)")
        elif cfg.is_manual:
            print("  next:   open prompts.md, generate the shots in Flow,")
            print("          save them into shots/, then run:")
            print(f"          python3 -m povflow.cli assemble {result.directory}")
        else:
            print("  video:  not assembled — raw clips are in shots/")
        print(f"  script: {result.script_path.name}")

    total = sum(r.usd_spent for r in results)
    if total:
        print(f"\nSpent this run: ${total:.2f}")
        print(f"Month to date:  ${store.spend_this_month():.2f} "
              f"of ${cfg.max_usd_per_month:.2f}")
    return 0


def cmd_assemble(args: argparse.Namespace) -> int:
    from .assemble import AssemblyError
    from .pipeline import assemble_folder

    cfg = load_config(args.config)
    try:
        out = assemble_folder(
            cfg, args.folder.resolve(), keep_intermediates=args.keep_intermediates
        )
    except AssemblyError as exc:
        print(f"Assembly failed: {exc}", file=sys.stderr)
        return 1
    print(f"\nDone: {out}")
    print("Record your voice-over against this file — see voiceover.txt.")
    return 0


def cmd_costs(args: argparse.Namespace) -> int:
    cfg = load_config(args.config)

    print(f"Backend:      {cfg.backend}"
          + ("  (shots chained for continuity)"
             if cfg.backend == "omni" and cfg.chain_shots else ""))

    if cfg.is_manual:
        # Credits, not dollars: manual runs are generated in Flow on the
        # subscription, which the API billing model does not describe at all.
        print(f"Plan:         {cfg.plan_credits} credits for "
              f"{cfg.plan_eur:.2f} EUR  ({cfg.eur_per_credit:.4f} EUR/credit)")
        print(f"Rate:         {cfg.credits_per_second:.2f} credit(s) per second")
        print(f"Episode:      {cfg.shots_per_episode} shots x {cfg.seconds_per_shot}s "
              f"= {cfg.episode_seconds}s -> {cfg.credits_per_episode:.0f} credits "
              f"(~{cfg.eur_per_episode_credits:.2f} EUR)")
        print(f"Plan covers:  about {cfg.episodes_per_plan} episode(s) per month")
        api_eur = 0.10 * cfg.episode_seconds / 1.08
        print(f"\nSame episode over the API would be ~{api_eur:.2f} EUR "
              f"({api_eur / max(cfg.eur_per_episode_credits, 1e-9):.0f}x more).")
        print("Credits do not grant API access, which is why this backend is manual.")
        return 0

    store = Store(cfg.state_db)
    spent = store.spend_this_month()
    print(f"Model:        {cfg.model} at {cfg.resolution}")
    print(f"Rate:         ${cfg.usd_per_second:.3f} per second of output")
    if cfg.chained_input_usd_per_shot:
        print(f"Chaining:     +${cfg.chained_input_usd_per_shot:.3f} per chained shot "
              f"(previous clip billed as input)")
    print(f"Episode:      {cfg.shots_per_episode} shots x {cfg.seconds_per_shot}s "
          f"= {cfg.episode_seconds}s -> ${cfg.usd_per_episode:.2f}")
    print(f"Run cap:      ${cfg.max_usd_per_run:.2f}")
    print(f"Month cap:    ${cfg.max_usd_per_month:.2f}")
    print(f"Spent (MTD):  ${spent:.2f}  ({spent / cfg.max_usd_per_month * 100:.0f}%)")
    remaining = max(0.0, cfg.max_usd_per_month - spent)
    print(f"Remaining:    ${remaining:.2f} "
          f"= about {int(remaining // cfg.usd_per_episode)} more episode(s)")
    print("\nKnown rates:")
    for key, rate in sorted(cfg.rates.items()):
        print(f"  {key:48s} ${rate:.3f}/s")
    return 0


def cmd_history(args: argparse.Namespace) -> int:
    cfg = load_config(args.config)
    store = Store(cfg.state_db)
    titles = store.recent_titles(args.count)
    if not titles:
        print("No episodes yet.")
        return 0
    print(f"Last {len(titles)} episode(s), newest first:\n")
    for title in titles:
        print(f"  {title}")
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    handlers = {
        "run": cmd_run, "assemble": cmd_assemble,
        "costs": cmd_costs, "history": cmd_history,
    }
    try:
        return handlers[args.command](args)
    except ConfigError as exc:
        print(f"Config error: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
